stages:
  - deploy

pages:
  stage: deploy
  image: alpine:latest
  script:
    - apk add markdown
    - ./ci/website.sh
  artifacts:
    paths:
      - public
  only:
    refs:
      - root
      - ci
