"""Independent second-order response of piecewise-constant noisy controls."""

from collections.abc import Mapping

import numpy as np
from scipy import sparse
from scipy.sparse.linalg import expm_multiply


def _real_array(value, name):
    array = np.asarray(value)
    if np.iscomplexobj(array):
        if np.any(array.imag != 0):
            raise ValueError(f"{name} must be real")
        array = array.real
    array = np.asarray(array, dtype=float)
    if not np.all(np.isfinite(array)):
        raise ValueError(f"{name} must be finite")
    return array


def _validate_inputs(dt, H, B, law):
    durations = _real_array(dt, "dt")
    if durations.ndim != 1 or durations.size == 0 or np.any(durations <= 0):
        raise ValueError("dt must be a nonempty vector of positive durations")
    control = np.asarray(H, dtype=complex)
    noise = np.asarray(B, dtype=complex)
    if (
        control.ndim != 3
        or control.shape[0] != durations.size
        or control.shape[1] == 0
        or control.shape[1] != control.shape[2]
    ):
        raise ValueError("H must have shape (segments, dimension, dimension)")
    if (
        noise.ndim != 4
        or noise.shape[0] != durations.size
        or noise.shape[2:] != control.shape[1:]
    ):
        raise ValueError("B must have shape (segments, channels, dimension, dimension)")
    for name, operators in (("H", control), ("B", noise)):
        if not np.all(np.isfinite(operators)):
            raise ValueError(f"{name} must be finite")
        if not np.allclose(
            operators, operators.swapaxes(-1, -2).conj(), rtol=1e-12, atol=1e-13
        ):
            raise ValueError(f"{name} must be Hermitian")
    if not isinstance(law, Mapping):
        raise ValueError("law must be a mapping")
    if not {"kind", "mixing", "sigma"}.issubset(law):
        raise ValueError("law must define kind, mixing, and sigma")
    kind = str(law["kind"]).lower()
    if kind not in {"static", "ou", "telegraph", "white", "broadband"}:
        raise ValueError(f"unsupported noise kind: {law['kind']!r}")
    amplitudes = _real_array(law["sigma"], "sigma")
    mixing = _real_array(law["mixing"], "mixing")
    if amplitudes.ndim != 1 or np.any(amplitudes < 0):
        raise ValueError("sigma must be a vector of nonnegative amplitudes")
    if mixing.shape != (noise.shape[1], amplitudes.size):
        raise ValueError("mixing must have shape (channels, latent)")
    if kind in {"ou", "telegraph", "broadband"}:
        if "rates" not in law:
            raise ValueError(f"rates are required for {kind} noise")
        rates = _real_array(law["rates"], "rates")
        if rates.shape != amplitudes.shape or np.any(rates < 0):
            raise ValueError("rates must be a nonnegative vector matching sigma")
        if kind == "telegraph":
            rates = 2 * rates
    else:
        rates = np.zeros_like(amplitudes)
    return durations, control, noise, mixing, amplitudes, rates, kind


def _liouvillian(operator):
    identity = np.eye(operator.shape[0])
    return sparse.csr_matrix(
        -1j * (np.kron(identity, operator) - np.kron(operator.T, identity))
    )


def quadratic_response(dt, H, B, law):
    """Return complex ``k2[d*d, d*d]`` with column-major vectorization.

    ``dt[S]`` is strictly positive, ``H[S,d,d]`` is the Hermitian control,
    and ``B[S,C,d,d]`` contains Hermitian noise operators including their
    segment sensitivities. All quantities use consistent units with hbar=1.
    ``law`` is a mapping with ``kind``, real ``mixing[C,M]``, nonnegative
    ``sigma[M]``, and, for OU/broadband/telegraph, nonnegative ``rates[M]``.
    Kind names are case-insensitive. Static and white laws ignore rates.

    Latent noises are independent, stationary, and zero mean. Static noise
    has covariance sigma**2; OU and broadband have covariance
    sigma**2 * exp(-rates * abs(t-u)); symmetric telegraph noise has
    covariance sigma**2 * exp(-2*rates * abs(t-u)). White noise uses
    sigma**2 * delta(t-u) in the Stratonovich convention. Each channel's
    noise is the specified linear mixture of the latent noises.

    Scaling every sigma by lambda defines the returned coefficient through
    ``Phi0.conj().T @ Phi(lambda) = I + lambda**2 * k2 + O(lambda**4)``.
    Phi0 is generated by H. This is the full Dyson coefficient, including
    its coherent part, not a finite-amplitude channel or finite difference.

    A triangular moment system propagates S0, one F per colored latent,
    and S2 through every segment without bath restarts. Its equations are
    S0' = L0 S0, F' = (L0-gamma) F + Lnoise S0, and
    S2' = L0 S2 + sum(Lnoise F), initially (I, 0, 0). For white noise the
    last source is instead sum(Lnoise**2) S0 / 2. Sparse exponential actions
    integrate each constant segment. Common amplitude normalization keeps
    weak-noise coefficients away from the absolute floating-point floor.
    Only the matrix is returned; inputs are not mutated.
    """
    durations, control, noise, mixing, amplitudes, rates, kind = _validate_inputs(
        dt, H, B, law
    )
    dimension = control.shape[-1]
    channel_dimension = dimension**2
    result = np.zeros((channel_dimension, channel_dimension), dtype=complex)
    if amplitudes.size == 0 or not np.any(amplitudes):
        return result
    amplitude_scale = np.max(amplitudes)
    latent_noise = np.einsum(
        "scij,cm,m->smij", noise, mixing, amplitudes / amplitude_scale,
        optimize=True,
    )
    identity = np.eye(dimension)
    latent_noise -= (
        np.trace(latent_noise, axis1=-2, axis2=-1)[..., None, None]
        * identity / dimension
    )
    active = np.any(latent_noise != 0, axis=(0, 2, 3))
    if not np.any(active):
        return result
    latent_noise = latent_noise[:, active]
    rates = rates[active]
    latent_count = rates.size
    block_count = 2 if kind == "white" else latent_count + 2
    state = np.zeros(
        (block_count * channel_dimension, channel_dimension), dtype=complex
    )
    state[:channel_dimension] = np.eye(channel_dimension)
    channel_identity = sparse.eye(channel_dimension, format="csr", dtype=complex)
    for duration, hamiltonian, operators in zip(durations, control, latent_noise):
        drift = _liouvillian(hamiltonian)
        couplings = [_liouvillian(operator) for operator in operators]
        blocks = [[None] * block_count for _ in range(block_count)]
        blocks[0][0] = drift
        blocks[-1][-1] = drift
        if kind == "white":
            diffusion = sparse.csr_matrix(drift.shape, dtype=complex)
            for coupling in couplings:
                diffusion += coupling @ coupling
            blocks[-1][0] = 0.5 * diffusion
        else:
            for index, (rate, coupling) in enumerate(zip(rates, couplings), start=1):
                blocks[index][index] = drift - rate * channel_identity
                blocks[index][0] = coupling
                blocks[-1][index] = coupling
        generator = sparse.bmat(blocks, format="csr")
        state = expm_multiply(duration * generator, state)
    result = state[:channel_dimension].conj().T @ state[-channel_dimension:]
    return result * amplitude_scale**2
