#include <math.h>
#include "./bp_dec.h"
#include "../lib_rand/lib_rand.h"
#include "../lib_math/fast_math.h"

//#include <time.h>   // test rand runtime

// delta's bound when applying BETA
const double DLT_BD = ( ((double)BETA-1)/(BETA+1) );   // r0/r1 > BETA   iff   dml > (BETA-1)/(BETA+1)


//-- Matrix vector multiply Ax = y (NOTE that binary code's GenSyndrome() is defined as this function)
/*void MatVecMultiply(a_matrix *A, uint8_t *x, uint8_t *y)
{
  int32_t n, n2m, m;
  memset(y , 0 , A->MM*sizeof(*y));

  //-- handle by summing N (Mx1)_columns
  for(n=0; n < A->NN ; n++) {
    if(x[n]) {
      for(n2m=0; n2m < A->num_n[n] ; n2m++) {
        m = A->nlist[n][n2m];
        y[m] ^= 1;
      }
    }
  }
}*/
//-- Matrix vector multiply A2*x = y
void Mat2VecMultiply(a2_matrix *A, uint8_t *x, uint8_t *y)
{
  int32_t n, n2m, m;
  memset(y , 0 , A->MM*sizeof(*y));

  //-- handle by summing N (Mx1)_columns
  for(n=0; n < A->NN ; n++) {
    if(x[n]) {
      for(n2m=0; n2m < A->num_n[n] ; n2m++) {
        m = A->nlist[n][n2m];
        y[m] ^= 1;
      }
    }
  }
}


//-- "Quantum" Gen Syndrome Ax = y (where A and x are over GF4 but y is over GF2 as additive code)
void Quan_GenSyndrome(a_matrix_GFQ *A, GFQ_t *x, GFQ_t *y)    // input check matrix, and will check M = N-K rows
{
  int32_t n, n2m, m;
  memset(y , 0 , A->MM*sizeof(*y));

  //-- handle by summing N (Mx1)_columns
  for(n=0; n < A->NN ; n++) {
    if(x[n]) {
      for(n2m=0; n2m < A->num_n[n] ; n2m++) {
        m = A->nlist[n][n2m];
        y[m] ^= ( (x[n]>>1) & A->nlist_val[n][n2m] ) ^ ( x[n] & (A->nlist_val[n][n2m]>>1) );
        //printf("n %d  m %d  x[n] %d  A->nlist_val[n][n2m] %d y[m]%d\n", n,m,x[n],A->nlist_val[n][n2m],y[m]);
      }
    }
  }
  //printf("x = ");   for(n=0; n < A->NN ; n++) printf("%u ", x[n]);   printf("\n");
  //printf("y = ");   for(m=0; m < A->MM ; m++) printf("%u ", y[m]);   printf("\n");
}

//-- COPY from Quan_GenSyndrome
void Quan_DegSyndrome(g_matrix_GFQ *G, GFQ_t *x, GFQ_t *y)  // input generator matrix, and will check M+2K = N+K rows
{
  int32_t n, n2m, m;
  memset(y , 0 , G->MM*sizeof(*y));

  //-- handle by summing N (Mx1)_columns
  for(n=0; n < G->NN ; n++) {
    if(x[n]) {
      for(n2m=0; n2m < G->num_n[n] ; n2m++) {
        m = G->nlist[n][n2m];
        y[m] ^= ( (x[n]>>1) & G->nlist_val[n][n2m] ) ^ ( x[n] & (G->nlist_val[n][n2m]>>1) );
      }
    }
  }
  //printf("x = ");   for(n=0; n < G->NN ; n++) printf("%u ", x[n]);   printf("\n");
  //printf("y = ");   for(m=0; m < G->MM ; m++) printf("%u ", y[m]);   printf("\n");
}

//-- COPY from Quan_DegSyndrome
// verified ok, but tests show NO observable speed up
/*void Quan_LogSyndrome(g_matrix_GFQ *G, GFQ_t *x, GFQ_t *y)  // input generator matrix, and will check ONLY 2K rows
{
  int32_t m, n, j;
  memset(y , 0 , G->MM*sizeof(*y));

  //-- handle ONLY last 2K rows
  for(m = G->MM - 2*K; m < G->MM; m++)
  for(j=0; j < G->num_m[m] ; j++)
  {
    n = G->mlist[m][j];
    if(x[n])
      y[m] ^= ( (x[n]>>1) & G->mlist_val[m][j] ) ^ ( x[n] & (G->mlist_val[m][j]>>1) );
  }
}*/


#if STOP_BY_C   //: syndrome generated by Check Nodes
static void ChkNode_GenSyndrome(a_matrix_GFQ *A, QBP_Ctl *bp)
{
  int32_t  m, n, j, q;
  double qlm[2]; //, dm_c[M];

/*
 //if(bp->iter <= MAX_ITER-25)
  //Quan_GenSyndrome(A, bp->tt, bp->zz);
 //else
  for(m=0; m < A->MM; m++) {
    dm_c[m] = 1.0;
    for(j=0; j < A->num_m[m]; j++) { dm_c[m] *= bp->dqml_c[m][j]; }

    if(dm_c[m]>0) bp->zz[m] = 0;
    else          bp->zz[m] = 1;
  }
*/

  for(m=0; m < A->MM; m++) {
    bp->dm_c[m] = 1.0;                  // reset dm_c
    for(j=0; j < A->num_m[m]; j++) {
      n = A->mlist[m][j];
      q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}

      switch (q) {
      case 1: qlm[0]=(bp->qn[n][0]+bp->qn[n][1]); qlm[1]=(bp->qn[n][2]+bp->qn[n][3]); break;
      case 2: qlm[0]=(bp->qn[n][0]+bp->qn[n][2]); qlm[1]=(bp->qn[n][1]+bp->qn[n][3]); break;
      case 3: qlm[0]=(bp->qn[n][0]+bp->qn[n][3]); qlm[1]=(bp->qn[n][1]+bp->qn[n][2]); break;
      }

    #if 1 // SOFT dqml_c: more flexible, for if need to do more computation by dqml_c
      qlm[0] = qlm[0]/(qlm[0] + qlm[1]);
      bp->dqml_c[m][j] = qlm[0]*2 - 1;
    #else // HARD dqml_c: more simpler, for if only need to do judgment by sign of dqml_c
      if(qlm[0]>qlm[1]) bp->dqml_c[m][j] =  1;
      else              bp->dqml_c[m][j] = -1;
    #endif

      bp->dm_c[m] *= bp->dqml_c[m][j];  // update dm_c
    }

    if(bp->dm_c[m]>0) bp->zz_c[m] = 0;
    else              bp->zz_c[m] = 1;
  }

  if( 0 == HamDist(bp->zz_c, bp->target_z, A->MM) )   bp->is_hit_c = 1;
  else                                                bp->is_hit_c = 0;
}
#endif

//-- return 1 if v is a zero vector; otherwise return 0
uint8_t is_zero_vec(GFQ_t *v, int32_t len)
{
  int32_t i;
  for(i=0; i<len; i++)
    if(v[i]) return 0;

  return 1;
}

//-- check Hamming weight of vector v
uint32_t HamWt(GFQ_t *v, int32_t len)
{
  uint32_t i, sum = 0;
  for (i=0; i<len; i++) { if (*v++ != 0) sum++; }
  return sum;
}

//-- check Hamming distance between x and y
uint32_t HamDist(GFQ_t *x, GFQ_t *y, int32_t len)
{
  uint32_t i, sum = 0;
  for (i = 0; i < len; i++) {
    if (*x++ != *y++) sum++;
  }
  return sum;
}

//-- get v = y - x over GF4
void VecDiff(GFQ_t *v, GFQ_t *y, GFQ_t *x, int32_t len)
{
  int32_t i;
  for (i = 0; i < len; i++) {
    if(x[i]==y[i])  v[i]=0;
    else            v[i] = y[i]^x[i];
  }
}


//-- COPY & modified from load_A();
void load_A_GFQ(FILE *fpA, a_matrix_GFQ *A)
{
const int dbg_prt=0;

  int32_t err, val;
  uint32_t val_Q;
  int32_t m, n, i, j;

/* (By convention (systematic form), the righthand M*M matrix is an invertible matrix FOR LINEAR CODE)
a_matrix_GFQ *A to
[1 2 2 1 0;
 0 1 2 2 1;
 1 0 1 2 2;
 2 1 0 1 2]
will have N=5; M=4,
  *num_n = [3 3 3 4 3], max_num_n = 4,
  *num_m = [4 4 4 4], max_num_m = 4,
  *nlist = [c1 c2 c3 c4 c5]     with *c1=[1 3 4], *c2=[1 2 4], *c3=[1 2 3], *c4=[1 2 3 4], *c5=[2 3 4], all -1 as index;
  *nlist_val = [v1 v2 v3 v4 v5] with *v1=[1 1 2], *v2=[2 1 1], *v3=[2 2 1], *v4=[1 2 2 1], *v5=[2 3 4];
  *mlist = [r1 r2 r3 r4]        with *r1=[1 2 3 4], *r2=[2 3 4 5], *r3=[1 3 4 5], *r4=[1 2 4 5], all -1 as index;;
  *mlist_val = [u1 u2 u3 u4 u5] with *u1=[1 2 2 1], *u2=[1 2 2 1], *u3=[1 1 2 2], *u4=[2 1 1 2];
  *ni2j = [j1 j2 j3 j4] with *j1=[0 0 0], *j2=[1 0 1], *j3=[2 1 1], *j4=[3 2 2 2], *j5=[3 3 3];
          j1 means in col_1 the three non-zeros are all the first non-zeros in row order
*/
  //---- load A, see comments above
  err = fscanf(fpA, "%d %d %d %d", &(A->NN), &(A->MM), &(A->max_num_n), &(A->max_num_m));
  if(err==EOF) { printf("scan A basic parm NG !!\n");  exit(1); }
  printf("A->[NN,MM,max_num_n,max_num_m] = [%d %d %d %d] \n", A->NN, A->MM, A->max_num_n, A->max_num_m);

  if(dbg_prt) printf(" num_n = ");
  for(n = 0 ; n < A->NN; n++) {
    err = fscanf(fpA, "%d", &(A->num_n[n]));
    if(dbg_prt) printf("%d ", A->num_n[n]);
  }
  if(err==EOF) { printf("scan A num_n NG !!\n");  exit(1); }

  if(dbg_prt) printf("\n num_m = ");
  for(m = 0 ; m < A->MM; m++) {
    err = fscanf(fpA, "%d", &(A->num_m[m]));
    if(dbg_prt) printf("%d ", A->num_m[m]);
  }
  if(err==EOF) { printf("scan A num_m NG !!\n");  exit(1); }

  if(dbg_prt) printf("\n");
  for(n=0 ; n < A->NN; n++) {
    A->nlist[n] = (int32_t*)calloc(A->num_n[n] , sizeof( *(A->nlist[n]) ) );
    A->nlist_val[n] = (GFQ_t*)calloc(A->num_n[n] , sizeof( *(A->nlist_val[n]) ) );
    for(i=0 ; i < A->num_n[n]; i++) {
      err = fscanf( fpA , "%d" , &val );  A->nlist[n][i] = val-1;
      err = fscanf( fpA , "%u" , &val_Q );  A->nlist_val[n][i] = val_Q;
    }
   if(dbg_prt){
    printf("idx:"); for(i=0; i < A->num_n[n]; i++) { printf( "%d @%p  " , A->nlist[n][i] , &(A->nlist[n][i]) ); }
    printf( "  from A->nlist[%d] %p  @%p \n" , n , A->nlist[n] , &(A->nlist[n]) );
    printf("val:"); for(i=0; i < A->num_n[n]; i++) { printf( "%u @%p  " , A->nlist_val[n][i] , &(A->nlist_val[n][i]) ); }
    printf( "  from A->nlist_val[%d] %p  @%p \n" , n , A->nlist_val[n] , &(A->nlist_val[n]) );
   }
    //- read out dummy
    for( ; i < A->max_num_n; i++) { err = fscanf(fpA, "%d", &val);  err = fscanf( fpA , "%u" , &val_Q ); }
    if(err==EOF) { printf("scan A nlist[%d] NG !!\n", n);  exit(1); }
  }

  for(m = 0 ; m < A->MM; m++) {
    A->mlist[m] = (int32_t*)calloc(A->num_m[m] , sizeof( *(A->mlist[m]) ) );
    A->mlist_val[m] = (GFQ_t*)calloc(A->num_m[m] , sizeof( *(A->mlist_val[m]) ) );
    for(j=0 ; j < A->num_m[m]; j++) {
      err = fscanf( fpA , "%d" , &val );  A->mlist[m][j] = val-1;
      err = fscanf( fpA , "%u" , &val_Q );  A->mlist_val[m][j] = val_Q;
    }
   if(dbg_prt){
    printf("idx:"); for(j=0; j < A->num_m[m]; j++) { printf( "%d @%p  " , A->mlist[m][j] , &(A->mlist[m][j]) ); }
    printf( "  from A->mlist[%d] %p  @%p \n" , m , A->mlist[m] , &(A->mlist[m]) );
    printf("val:"); for(j=0; j < A->num_m[m]; j++) { printf( "%u @%p  " , A->mlist_val[m][j] , &(A->mlist_val[m][j]) ); }
    printf( "  from A->mlist_val[%d] %p  @%p \n" , m , A->mlist_val[m] , &(A->mlist_val[m]) );
   }
    //- read out dummy
    for( ; j < A->max_num_m; j++) { err = fscanf(fpA, "%d", &val);  err = fscanf( fpA , "%u" , &val_Q ); }
    if(err==EOF) { printf("scan A mlist[%d] NG !!\n", m);  exit(1); }
  }

  err = fscanf(fpA, "%d", &val);
  if(err==EOF)  printf("load A done and success!\n");
  else        { printf("load A done but not hit EOF , NG !!\n");  exit(1); }

  if(A->NN != N || A->MM != M) { printf("A->[NN,MM] not match main [N,M] !!\n");  exit(1); }
  //printf("press enter to continue...\n"); getchar();

  //====================================================
  //-- construct ni2j
  int32_t LM[M];  memset(LM, 0, M*sizeof(int32_t));
  for(n=0 ; n < A->NN; n++) {
    A->ni2j[n] = (int32_t*)calloc(A->num_n[n] , sizeof( *(A->ni2j[n]) ) );
    for(i=0 ; i < A->num_n[n]; i++) {
      m = A->nlist[n][i];
      A->ni2j[n][i] = LM[m];    LM[m]++;
      if(dbg_prt)  printf("%d ", A->ni2j[n][i]);
    }
    if(dbg_prt) printf(" in ni2j[%d]\n", n);
  }
  //-- construct mj22
  int32_t LN[N];  memset(LN, 0, sizeof(LN));
  for(m=0; m < A->MM; m++) {
    A->mj2i[m] = (int32_t*)calloc(A->num_m[m] , sizeof( *(A->mj2i[m]) ) );
    for(j=0; j < A->num_m[m]; j++) {
      n = A->mlist[m][j];
      A->mj2i[m][j] = LN[n];    LN[n]++;
    }
  }

  //printf("press enter to continue...\n"); getchar();
}

//-- COPY from load_A_GFQ
void load_G_GFQ(FILE *fpA, g_matrix_GFQ *A)
{
const int dbg_prt=0;

  int32_t err, val;
  uint32_t val_Q;
  int32_t m, n, i, j;
  //---- load A, see comments above
  err = fscanf(fpA, "%d %d %d %d", &(A->NN), &(A->MM), &(A->max_num_n), &(A->max_num_m));
  if(err==EOF) { printf("scan G basic parm NG !!\n");  exit(1); }
  printf("G->[NN,MM,max_num_n,max_num_m] = [%d %d %d %d] \n", A->NN, A->MM, A->max_num_n, A->max_num_m);

  if(dbg_prt) printf(" num_n = ");
  for(n = 0 ; n < A->NN; n++) {
    err = fscanf(fpA, "%d", &(A->num_n[n]));
    if(dbg_prt) printf("%d ", A->num_n[n]);
  }
  if(err==EOF) { printf("scan A num_n NG !!\n");  exit(1); }

  if(dbg_prt) printf("\n num_m = ");
  for(m = 0 ; m < A->MM; m++) {
    err = fscanf(fpA, "%d", &(A->num_m[m]));
    if(dbg_prt) printf("%d ", A->num_m[m]);
  }
  if(err==EOF) { printf("scan A num_m NG !!\n");  exit(1); }

  if(dbg_prt) printf("\n");
  for(n=0 ; n < A->NN; n++) {
    A->nlist[n] = (int32_t*)calloc(A->num_n[n] , sizeof( *(A->nlist[n]) ) );
    A->nlist_val[n] = (GFQ_t*)calloc(A->num_n[n] , sizeof( *(A->nlist_val[n]) ) );
    for(i=0 ; i < A->num_n[n]; i++) {
      err = fscanf( fpA , "%d" , &val );  A->nlist[n][i] = val-1;
      err = fscanf( fpA , "%u" , &val_Q );  A->nlist_val[n][i] = val_Q;
    }
   if(dbg_prt){
    printf("idx:"); for(i=0; i < A->num_n[n]; i++) { printf( "%d @%p  " , A->nlist[n][i] , &(A->nlist[n][i]) ); }
    printf( "  from A->nlist[%d] %p  @%p \n" , n , A->nlist[n] , &(A->nlist[n]) );
    printf("val:"); for(i=0; i < A->num_n[n]; i++) { printf( "%u @%p  " , A->nlist_val[n][i] , &(A->nlist_val[n][i]) ); }
    printf( "  from A->nlist_val[%d] %p  @%p \n" , n , A->nlist_val[n] , &(A->nlist_val[n]) );
   }
    //- read out dummy
    for( ; i < A->max_num_n; i++) { err = fscanf(fpA, "%d", &val);  err = fscanf( fpA , "%u" , &val_Q ); }
    if(err==EOF) { printf("scan A nlist[%d] NG !!\n", n);  exit(1); }
  }

  for(m = 0 ; m < A->MM; m++) {
    A->mlist[m] = (int32_t*)calloc(A->num_m[m] , sizeof( *(A->mlist[m]) ) );
    A->mlist_val[m] = (GFQ_t*)calloc(A->num_m[m] , sizeof( *(A->mlist_val[m]) ) );
    for(j=0 ; j < A->num_m[m]; j++) {
      err = fscanf( fpA , "%d" , &val );  A->mlist[m][j] = val-1;
      err = fscanf( fpA , "%u" , &val_Q );  A->mlist_val[m][j] = val_Q;
    }
   if(dbg_prt){
    printf("idx:"); for(j=0; j < A->num_m[m]; j++) { printf( "%d @%p  " , A->mlist[m][j] , &(A->mlist[m][j]) ); }
    printf( "  from A->mlist[%d] %p  @%p \n" , m , A->mlist[m] , &(A->mlist[m]) );
    printf("val:"); for(j=0; j < A->num_m[m]; j++) { printf( "%u @%p  " , A->mlist_val[m][j] , &(A->mlist_val[m][j]) ); }
    printf( "  from A->mlist_val[%d] %p  @%p \n" , m , A->mlist_val[m] , &(A->mlist_val[m]) );
   }
    //- read out dummy
    for( ; j < A->max_num_m; j++) { err = fscanf(fpA, "%d", &val);  err = fscanf( fpA , "%u" , &val_Q ); }
    if(err==EOF) { printf("scan A mlist[%d] NG !!\n", m);  exit(1); }
  }

  err = fscanf(fpA, "%d", &val);
  if(err==EOF)  printf("load G done and success!\n");
  else        { printf("load G done but not hit EOF , NG !!\n");  exit(1); }

  if(A->NN != N || A->MM != M_G) { printf("G->[NN,MM] not match main [N,M_G] !!\n");  exit(1); }
  //printf("press enter to continue...\n"); getchar();

  //====================================================
  //-- construct ni2j
  int32_t LM[M_G];  memset(LM, 0, M_G*sizeof(int32_t));
  for(n=0 ; n < A->NN; n++) {
    A->ni2j[n] = (int32_t*)calloc(A->num_n[n] , sizeof( *(A->ni2j[n]) ) );
    for(i=0 ; i < A->num_n[n]; i++) {
      m = A->nlist[n][i];
      A->ni2j[n][i] = LM[m];    LM[m]++;
      if(dbg_prt)  printf("%d ", A->ni2j[n][i]);
    }
    if(dbg_prt) printf(" in ni2j[%d]\n", n);
  }
  //printf("press enter to continue...\n"); getchar();
}


//-- alloc for "Quantum" BP Ctrl Blk
void alloc_QBPC(a_matrix_GFQ *A, QBP_Ctl *bp)
{
  int32_t  m, n;

  for(m=0; m < A->MM; m++) {
    bp->dml[m] = (double*)calloc(A->num_m[m], sizeof( *(bp->dml[m]) ) );
    bp->rml[m] = (double(*)[2])calloc(A->num_m[m], sizeof( *(bp->rml[m]) ) );
    bp->dqml[m] = (double*)calloc(A->num_m[m], sizeof( *(bp->dqml[m]) ) );
  #if EN_AFP_V
    bp->dqml_ori[m] = calloc(A->num_m[m], sizeof( *(bp->dqml_ori[m]) ) );
  #endif
  #if STOP_BY_C
    bp->dqml_c[m] = calloc(A->num_m[m], sizeof( *(bp->dqml_c[m]) ) );
  #endif
  }

  /*for(n=0; n < A->NN; n++) {
    bp->qlm[n] = calloc(A->num_n[n], sizeof( *(bp->qlm[n]) ) );   // not need as will pass by dqml
  }*/


  //====================================================
#if CYC_CHK
  int32_t i, j, i2, m2, j2, n2, ii,ii2;

  for(n=0; n < A->NN; n++){
    bp->cyc_cnt[n] = calloc( A->num_n[n] , sizeof( *(bp->cyc_cnt[n]) ) );
    bp->cycs[n] = calloc( A->num_n[n] , sizeof( *(bp->cycs[n]) ) );
    for(i=0 ; i < A->num_n[n]; i++)  bp->cycs[n][i] = calloc( A->num_n[n], sizeof(*(bp->cycs[n][i])) );
  }
  for(m=0; m < A->MM; m++) {
    bp->rml2[m] = calloc(A->num_m[m], sizeof( *(bp->rml2[m]) ) );
  }

  // ======== to init bp->cyc_cnt ======== //
  //
  // n        n2
  // m ------ m  ... (run all n2)
  // |        |
  // m2------ 1?
  // :
  // and (run all m2)

  for(n=0 ; n < A->NN; n++)
  for(i=0 ; i < A->num_n[n]-1; i++) {
    m = A->nlist[n][i];
    //----------- (run all m2)
    for(i2=i+1; i2 < A->num_n[n]; i2++) {
      m2 = A->nlist[n][i2];
      j = A->ni2j[n][i] + 1;    // +1 to get first n2
      j2 = A->ni2j[n][i2] + 1;  // +1 to (if match will) get n2
      for( ; j < A->num_m[m]; j++) {  // (run all n2)
        n2 = A->mlist[m][j];
        for( ; j2 < A->num_m[m2]; j2++) // check if hit 1? (as above fig): if hit => a four-cycle at bit n's i,i2
          if(A->mlist[m2][j2]==n2) { ii = A->mj2i[m][j];  ii2 = A->mj2i[m2][j2];   // need to convert to bit n2's ii,ii2
            bp->cyc_cnt[n][i]++; bp->cyc_cnt[n][i2]++; bp->cyc_cnt[n2][ii]++; bp->cyc_cnt[n2][ii2]++;}
          else if(A->mlist[m2][j2]>n2) break; // to move to next j (i.e. next n2)
      }
    }
    //-----------------------
  }

  #if 0 // set to 0 to disable
  for(n=0; n < A->NN; n++) { // debug print
    for(i=0 ; i < A->num_n[n]; i++) { printf("%d ", bp->cyc_cnt[n][i]); }
    printf(" = bp->cyc_cnt[%d]\n", n);  //getchar();
  } getchar();
  #endif

  // ======== to init bp->cycs (a little bit similar to above) ======== //
  for(n=0 ; n < A->NN; n++)
  for(i=0 ; i < A->num_n[n]-1; i++) {
    m = A->nlist[n][i];
    //----------- (run all m2)
    for(i2=i+1; i2 < A->num_n[n]; i2++) {
      m2 = A->nlist[n][i2];
      j = A->ni2j[n][i] + 1;    // +1 to get first n2
      j2 = A->ni2j[n][i2] + 1;  // +1 to (if match will) get n2
      for( ; j < A->num_m[m]; j++) {  // (run all n2)
        n2 = A->mlist[m][j];
        for( ; j2 < A->num_m[m2]; j2++) // check if hit 1? (as above fig): if hit => a four-cycle at bit n's i,i2
          if(A->mlist[m2][j2]==n2) { ii = A->mj2i[m][j];  ii2 = A->mj2i[m2][j2];   // need to convert to bit n2's ii,ii2
            bp->cycs[n][i][i2]++; bp->cycs[n][i2][i]++; bp->cycs[n2][ii][ii2]++; bp->cycs[n2][ii2][ii]++;}
          else if(A->mlist[m2][j2]>n2) break; // to move to next j (i.e. next n2)
      }
    }
    //-----------------------
  }

  #if 0 // set to 0 to disable
  for(n=0; n < A->NN; n++) { // debug print
    for(i=0; i < A->num_n[n]; i++) {
      for(i2=0; i2 < A->num_n[n]; i2++) { printf("%d ", bp->cycs[n][i][i2]); }
      printf("   ");
    }
    printf(" = bp->cycs[%d]\n", n);  //getchar();
  } getchar();
  #endif

#endif  // END of CYC_CHK


#if BY_DEC != 25    // default serial order
  for(n=0; n<N; n++) { bp->seq[n] = n; }

  #if RND_SCHE == 1
  //time_t  tStr;  tStr = time(NULL);   for(n=0; n<0xfffffff; n++) { m = rv_Nminus1(N); } // a discrete r.v. over {0, 1, 2, ..., N-1}
  //printf("rv_Nminus1 runtime : %ld sec \n", time(NULL) - tStart); getchar();

  int32_t n1, tmp_n;   uint64_t seq_seed[4];   rnd256_init_priv(seq_seed);
  for(n=0; n<N-1; n++) {                  //-- cite https://danluu.com/sattolo/
    //n1 = priv_Nminus1(N, seq_seed);       // a discrete r.v. over {0, 1, 2, ..., N-1}   // Fisher-Yates approach (may multi-cycles)
    n1 = priv_IntAB(n+1, N-1, seq_seed);  // a discrete r.v. over {n+1,n+2, ..., N-1}   // Sattolo approach  (guaranteed one cycle)
    tmp_n = bp->seq[n];   bp->seq[n] = bp->seq[n1];   bp->seq[n1] = tmp_n;  // swap idxs at [n] and [n1]
  }
  #endif

#elif BY_DEC == 25
  #if ORI==4115 || ORI==13134   // [[13,1,3]] code, Surface Code, X (M=N-1), extended 4 redundant rows
          // [[41,1,5]] code, Surface Code, X (M=N-1)
    #if Surf_L == 2
  int32_t seq[N] = {0,1,2,7,12,11,10,5,3,4,9,8,6};   // circ
    #elif Surf_L == 4
  int32_t seq[N] = {0,1,2,3,4, 13,22,31,40, 39,38,37,36, 27,18,9, 5,6,7,8, 17,26,35, 34,33,32, 23,14, 10,11,12, 21,30, 29,28, 19, 15,16, 25,24,20};   // circ
  //int32_t seq[N] = {0,4,40,36, 1,2,3, 13,22,31, 39,38,37, 27,18,9, 5,6,7,8, 17,26,35, 34,33,32, 23,14, 10,11,12, 21,30, 29,28, 19, 15,16, 25,24,20};  // corner first
  //int32_t seq[N] = {0,1,2,3,4, 13,22,31,40, 39,38,37,36, 27,18,9, 5,6,7,8, 10,11,12, 14,15,16,17, 19,20,21, 23,24,25,26, 28,29,30, 32,33,34,35};      // cseq: circ then seq
  //int32_t seq[N] = {20,24,25,16,15,19,28,29,30,21,12,11,10,14,23,32,33,34,35,26,17,8,7,6,5,9,18,27,36,37,38,39,40,31,22,13,4,3,2,1,0};   // circ_inv (tested, not good)
    #elif Surf_L == 6
  int32_t seq[N] = {0,1,2,3,4,5,6,19,32,45,58,71,84,83,82,81,80,79,78,65,52,39,26,13,7,8,9,10,11,12,25,38,51,64,77,76,75,74,73,72,59,46,33,20,14,15,16,17,18,31,44,57,70,69,68,67,66,53,40,27,21,22,23,24,37,50,63,62,61,60,47,34,28,29,30,43,56,55,54,41,35,36,49,48,42};   // circ
    #elif Surf_L == 8
  int32_t seq[N] = {0,1,2,3,4,5,6,7,8,25,42,59,76,93,110,127,144,143,142,141,140,139,138,137,136,119,102,85,68,51,34,17,9,10,11,12,13,14,15,16,33,50,67,84,101,118,135,134,133,132,131,130,129,128,111,94,77,60,43,26,18,19,20,21,22,23,24,41,58,75,92,109,126,125,124,123,122,121,120,103,86,69,52,35,27,28,29,30,31,32,49,66,83,100,117,116,115,114,113,112,95,78,61,44,36,37,38,39,40,57,74,91,108,107,106,105,104,87,70,53,45,46,47,48,65,82,99,98,97,96,79,62,54,55,56,73,90,89,88,71,63,64,81,80,72};   // circ
    #elif Surf_L == 10
  int32_t seq[N] = {0,1,2,3,4,5,6,7,8,9,10,31,52,73,94,115,136,157,178,199,220,219,218,217,216,215,214,213,212,211,210,189,168,147,126,105,84,63,42,21,11,12,13,14,15,16,17,18,19,20,41,62,83,104,125,146,167,188,209,208,207,206,205,204,203,202,201,200,179,158,137,116,95,74,53,32,22,23,24,25,26,27,28,29,30,51,72,93,114,135,156,177,198,197,196,195,194,193,192,191,190,169,148,127,106,85,64,43,33,34,35,36,37,38,39,40,61,82,103,124,145,166,187,186,185,184,183,182,181,180,159,138,117,96,75,54,44,45,46,47,48,49,50,71,92,113,134,155,176,175,174,173,172,171,170,149,128,107,86,65,55,56,57,58,59,60,81,102,123,144,165,164,163,162,161,160,139,118,97,76,66,67,68,69,70,91,112,133,154,153,152,151,150,129,108,87,77,78,79,80,101,122,143,142,141,140,119,98,88,89,90,111,132,131,130,109,99,100,121,120,110};   // circ
    #elif Surf_L == 12
  int32_t seq[N] = {0,1,2,3,4,5,6,7,8,9,10,11,12,37,62,87,112,137,162,187,212,237,262,287,312,311,310,309,308,307,306,305,304,303,302,301,300,275,250,225,200,175,150,125,100,75,50,25,13,14,15,16,17,18,19,20,21,22,23,24,49,74,99,124,149,174,199,224,249,274,299,298,297,296,295,294,293,292,291,290,289,288,263,238,213,188,163,138,113,88,63,38,26,27,28,29,30,31,32,33,34,35,36,61,86,111,136,161,186,211,236,261,286,285,284,283,282,281,280,279,278,277,276,251,226,201,176,151,126,101,76,51,39,40,41,42,43,44,45,46,47,48,73,98,123,148,173,198,223,248,273,272,271,270,269,268,267,266,265,264,239,214,189,164,139,114,89,64,52,53,54,55,56,57,58,59,60,85,110,135,160,185,210,235,260,259,258,257,256,255,254,253,252,227,202,177,152,127,102,77,65,66,67,68,69,70,71,72,97,122,147,172,197,222,247,246,245,244,243,242,241,240,215,190,165,140,115,90,78,79,80,81,82,83,84,109,134,159,184,209,234,233,232,231,230,229,228,203,178,153,128,103,91,92,93,94,95,96,121,146,171,196,221,220,219,218,217,216,191,166,141,116,104,105,106,107,108,133,158,183,208,207,206,205,204,179,154,129,117,118,119,120,145,170,195,194,193,192,167,142,130,131,132,157,182,181,180,155,143,144,169,168,156};   // circ
    #elif Surf_L == 14
  int32_t seq[N] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,43,72,101,130,159,188,217,246,275,304,333,362,391,420,419,418,417,416,415,414,413,412,411,410,409,408,407,406,377,348,319,290,261,232,203,174,145,116,87,58,29,15,16,17,18,19,20,21,22,23,24,25,26,27,28,57,86,115,144,173,202,231,260,289,318,347,376,405,404,403,402,401,400,399,398,397,396,395,394,393,392,363,334,305,276,247,218,189,160,131,102,73,44,30,31,32,33,34,35,36,37,38,39,40,41,42,71,100,129,158,187,216,245,274,303,332,361,390,389,388,387,386,385,384,383,382,381,380,379,378,349,320,291,262,233,204,175,146,117,88,59,45,46,47,48,49,50,51,52,53,54,55,56,85,114,143,172,201,230,259,288,317,346,375,374,373,372,371,370,369,368,367,366,365,364,335,306,277,248,219,190,161,132,103,74,60,61,62,63,64,65,66,67,68,69,70,99,128,157,186,215,244,273,302,331,360,359,358,357,356,355,354,353,352,351,350,321,292,263,234,205,176,147,118,89,75,76,77,78,79,80,81,82,83,84,113,142,171,200,229,258,287,316,345,344,343,342,341,340,339,338,337,336,307,278,249,220,191,162,133,104,90,91,92,93,94,95,96,97,98,127,156,185,214,243,272,301,330,329,328,327,326,325,324,323,322,293,264,235,206,177,148,119,105,106,107,108,109,110,111,112,141,170,199,228,257,286,315,314,313,312,311,310,309,308,279,250,221,192,163,134,120,121,122,123,124,125,126,155,184,213,242,271,300,299,298,297,296,295,294,265,236,207,178,149,135,136,137,138,139,140,169,198,227,256,285,284,283,282,281,280,251,222,193,164,150,151,152,153,154,183,212,241,270,269,268,267,266,237,208,179,165,166,167,168,197,226,255,254,253,252,223,194,180,181,182,211,240,239,238,209,195,196,225,224,210};   // circ
    #else
  XXX_NOT_SUPPORT_XXX
    #endif
  memcpy(bp->seq , seq , sizeof(bp->seq));

  #elif ORI==2515 // [[25,1,5]] code, Surface Code ROTATED (also support XZZX)
    /*#if Surf_d == 3
  int32_t seq[N] = {1,3,7,9, 2,8, 4,6, 5};  // 4 groups
    #elif Surf_d == 5
  int32_t seq[N] = {1,3,5,11,13,15,21,23,25, 2,4,12,14,22,24, 6,8,10,16,18,20, 7,9,17,19};  // 4 groups
    #elif Surf_d == 7
  int32_t seq[N] = {1,3,5,7,15,17,19,21,29,31,33,35,43,45,47,49, 2,4,6,16,18,20,30,32,34,44,46,48, 8,10,12,14,22,24,26,28,36,38,40,42, 9,11,13,23,25,27,37,39,41};  // 4 groups
    #else
  XXX_NOT_SUPPORT_XXX
    #endif */
  //-- now auto-done as follows
  int32_t seq[N];   int32_t  gp,row,col;  // partition into 4 groups
  n=0;
  for(gp=0; gp < 4; gp++) {
    for(row=gp/2; row < Surf_d; row+=2)
    for(col=gp%2; col < Surf_d; col+=2) {
      seq[n] = row*Surf_d + col + 1;    n++;      //printf("%d ", n);
    }
  }                                               //printf("\n");
  //for(n=0;n<N;n++) { printf("%d ", seq[n]);}      printf("\n"); getchar();
  for(n=0;n<N;n++) { seq[n] = seq[n] - 1; }
  memcpy( bp->seq , seq , sizeof(bp->seq) );

  #else
  XXX_NOT_SUPPORT_XXX
  #endif
#endif
}

//#define dlt (1e-2)
//#define dlt (1e-3)
//#define dlt (1e-4)
//#define dlt (1e-5)
//#define dlt (1e-8)
#define dlt   (1e-11)   // note, log10((2e-11)^30) = -320.97  (still > DBL_MIN 5e-324  even if  row_wt=30);
//#define dlt (1e-12)
//#define dlt (1e-13)
//#define dlt (1e-14)
//#define dlt (1e-15)
//#define dlt (1e-16)
//#define dlt (1e-18)
//#define dlt (1e-20)
//#define dlt (1e-24)
//#define dlt (1e-32)

//#define dlt_b (1e-15)   // also need 1e-15 > 2^-52 (=2.22e-16) to let (1.0-dlt_b) not underflow.
#define dlt_b (dlt)     // actually need dlt_b=1e-11 too to let (rml_1)^cw = (dlt_b)^cw not underflow for col_wt (cw)=30

#define restrict_p2(p) \
{ \
  if(p[0] < dlt_b) { \
    p[0] = dlt_b;     p[1] = 1.0 - dlt_b; \
/*printf("\n\n hit p[0]~=0 \n\n");*/\
  } \
  else if(p[0] > 1.0 - dlt_b) { \
    p[0] = 1.0 - dlt_b;     p[1] = dlt_b; \
/*printf("\n\n hit p[0]~=1 \n\n");*/\
  } \
  else if(0.5-dlt<p[0]&&p[0]<0.5+dlt) { \
    if(p[0] < 0.5) { p[0] = 0.5-dlt; p[1] = 0.5+dlt; } \
    else { p[0] = 0.5+dlt; p[1] = 0.5-dlt; } \
/*printf("\n\n hit p[0]~=0.5 \n\n");*/\
  } \
  else { p[1] = 1.0 - p[0]; } \
}

// init_p[Q]: init p_vec over {I,X,Z,Y}
// init_d[Q-1]: (delta) d_vec over {X,Z,Y}
// p_ch: channel err rate (dep ch: eps = p_ch/3;  inde X-Z ch: pX = pZ = p_ch)
static void GenInitBiasVec(double *init_p, double *init_d, double p_ch)  // also apply CH_TYPE and ALFA_V insider
{
  if(Q!=4)  { printf("Q=%u , but must =4 ! exit() !!", Q);  getchar();  exit(1); }
  int32_t q;

#if AFN
  double p_ch2[2];
  p_ch2[0] = 1.0 - p_ch;                        p_ch2[1] = p_ch;
  p_ch2[0] = pow_fast(p_ch2[0], 10.0/AFN);      p_ch2[1] = pow_fast(p_ch2[1], 10.0/AFN);
  p_ch2[0] = p_ch2[0]/(p_ch2[0] + p_ch2[1]);    //restrict_p2(p_ch2);   // bound p_ch2[0] and gen p_ch2[1]
  p_ch = p_ch2[1]/(p_ch2[0] + p_ch2[1]);  // overwrite p_ch
#endif


  //-- init_p
#if CH_TYPE==0    // dep ch
  init_p[0] = (1.0 - p_ch);
  for(q=1;q<Q;q++) { init_p[q] = p_ch/(Q-1); }
#elif CH_TYPE==1  // indep X-Z ch
  double pY=p_ch*p_ch , pX=p_ch-pY , pZ=p_ch-pY , pI=1.0-pX-pZ-pY ;
  // this will make -pI*log2(pI)-pX*log2(pX)-pZ*log2(pZ)-pY*log2(pY) = [ -(1-p_ch)*log2(1-p_ch)-p_ch*log2(p_ch) ]*2
  init_p[0]=pI;  init_p[1]=pX;  init_p[2]=pZ;  init_p[3]=pY;
#else
  XXX_NG_CH_TYPE_XXX
#endif

  //-- init_d
  for(q=1;q<Q;q++) {
  #if ALFA_V == 0   // DEFAULT MODE
    init_d[q-1] = 2*(init_p[0]+init_p[q]) - 1;  // d = p0-p1 = 2p0 -1, where p0 = pI+pX, pI+pZ, pI+pY for q=1,2,3 respectively
  #else   // enable ALFA_V
    double qlm[2];
    qlm[0] = init_p[0]+init_p[q];               qlm[1] = 1.0 - qlm[0];
    qlm[0] = pow_fast( qlm[0] , 10.0/ALFA_V );  qlm[1] = pow_fast( qlm[1] , 10.0/ALFA_V );
    qlm[0] = qlm[0]/(qlm[0] + qlm[1]);          //restrict_p2(qlm);   // bound qlm[0] and gen qlm[1]
    init_d[q-1] = 2*qlm[0] - 1;
  #endif
    if(fabs(init_d[q-1]) < 2*dlt) { printf("too small abs init_d[%d] %g , debug !!! \n", q-1, init_d[q-1]); getchar(); }
  }
}


/*//-- initialize majority voting
static void init_votes(QBP_Ctl *bp , GFQ_t *zz , a_matrix_GFQ *A)
{
#if BY_DEC == 26 && ORI==4115   // only support surface codes
  int32_t  m , n , i , j , votes[N];
  memset(votes , 0 , sizeof(votes));  // reset all to zeros

  for(m=0; m<M; m++) if(zz[m]) // when zz[m] non-zero:
  for(j=0; j < A->num_m[m]; j++) {
    n = A->mlist[m][j];
    votes[n] ++ ;
  }

  //- non-zero votes first  (result not good)
//  i = 0;
//  for(n=0; n<N; n++) if(votes[n]!=0) { bp->seq[i] = n;  i++; }  // collect non-zero vote (to do serial decoding first)
//  for(n=0; n<N; n++) if(votes[n]==0) { bp->seq[i] = n;  i++; }  // collect zero vote (to fill all for serial decoding)

  //- find max element in votes, and start seq from it  (result not good)
//  i = 0;  // used as max val
//  for(n=0; n<N; n++) if(votes[n]>i) { i = votes[n];  j = n; }
//  for(n=0; n<N; n++) { bp->seq[n] = (n+j)%N; }

  //- find max element in votes, start from it, and then circular   (result not good)
    #if Surf_L == 2
  int32_t seq[N] = {0,1,2,7,12,11,10,5,3,4,9,8,6};   // circ
    #elif Surf_L == 4
  int32_t seq[N] = {0,1,2,3,4, 13,22,31,40, 39,38,37,36, 27,18,9, 5,6,7,8, 17,26,35, 34,33,32, 23,14, 10,11,12, 21,30, 29,28, 19, 15,16, 25,24,20};   // circ
    #elif Surf_L == 6
  int32_t seq[N] = {0,1,2,3,4,5,6,19,32,45,58,71,84,83,82,81,80,79,78,65,52,39,26,13,7,8,9,10,11,12,25,38,51,64,77,76,75,74,73,72,59,46,33,20,14,15,16,17,18,31,44,57,70,69,68,67,66,53,40,27,21,22,23,24,37,50,63,62,61,60,47,34,28,29,30,43,56,55,54,41,35,36,49,48,42};   // circ
    #elif Surf_L == 8
  int32_t seq[N] = {0,1,2,3,4,5,6,7,8,25,42,59,76,93,110,127,144,143,142,141,140,139,138,137,136,119,102,85,68,51,34,17,9,10,11,12,13,14,15,16,33,50,67,84,101,118,135,134,133,132,131,130,129,128,111,94,77,60,43,26,18,19,20,21,22,23,24,41,58,75,92,109,126,125,124,123,122,121,120,103,86,69,52,35,27,28,29,30,31,32,49,66,83,100,117,116,115,114,113,112,95,78,61,44,36,37,38,39,40,57,74,91,108,107,106,105,104,87,70,53,45,46,47,48,65,82,99,98,97,96,79,62,54,55,56,73,90,89,88,71,63,64,81,80,72};   // circ
    #elif Surf_L == 10
  int32_t seq[N] = {0,1,2,3,4,5,6,7,8,9,10,31,52,73,94,115,136,157,178,199,220,219,218,217,216,215,214,213,212,211,210,189,168,147,126,105,84,63,42,21,11,12,13,14,15,16,17,18,19,20,41,62,83,104,125,146,167,188,209,208,207,206,205,204,203,202,201,200,179,158,137,116,95,74,53,32,22,23,24,25,26,27,28,29,30,51,72,93,114,135,156,177,198,197,196,195,194,193,192,191,190,169,148,127,106,85,64,43,33,34,35,36,37,38,39,40,61,82,103,124,145,166,187,186,185,184,183,182,181,180,159,138,117,96,75,54,44,45,46,47,48,49,50,71,92,113,134,155,176,175,174,173,172,171,170,149,128,107,86,65,55,56,57,58,59,60,81,102,123,144,165,164,163,162,161,160,139,118,97,76,66,67,68,69,70,91,112,133,154,153,152,151,150,129,108,87,77,78,79,80,101,122,143,142,141,140,119,98,88,89,90,111,132,131,130,109,99,100,121,120,110};   // circ
    #elif Surf_L == 12
  int32_t seq[N] = {0,1,2,3,4,5,6,7,8,9,10,11,12,37,62,87,112,137,162,187,212,237,262,287,312,311,310,309,308,307,306,305,304,303,302,301,300,275,250,225,200,175,150,125,100,75,50,25,13,14,15,16,17,18,19,20,21,22,23,24,49,74,99,124,149,174,199,224,249,274,299,298,297,296,295,294,293,292,291,290,289,288,263,238,213,188,163,138,113,88,63,38,26,27,28,29,30,31,32,33,34,35,36,61,86,111,136,161,186,211,236,261,286,285,284,283,282,281,280,279,278,277,276,251,226,201,176,151,126,101,76,51,39,40,41,42,43,44,45,46,47,48,73,98,123,148,173,198,223,248,273,272,271,270,269,268,267,266,265,264,239,214,189,164,139,114,89,64,52,53,54,55,56,57,58,59,60,85,110,135,160,185,210,235,260,259,258,257,256,255,254,253,252,227,202,177,152,127,102,77,65,66,67,68,69,70,71,72,97,122,147,172,197,222,247,246,245,244,243,242,241,240,215,190,165,140,115,90,78,79,80,81,82,83,84,109,134,159,184,209,234,233,232,231,230,229,228,203,178,153,128,103,91,92,93,94,95,96,121,146,171,196,221,220,219,218,217,216,191,166,141,116,104,105,106,107,108,133,158,183,208,207,206,205,204,179,154,129,117,118,119,120,145,170,195,194,193,192,167,142,130,131,132,157,182,181,180,155,143,144,169,168,156};   // circ
    #elif Surf_L == 14
  int32_t seq[N] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,43,72,101,130,159,188,217,246,275,304,333,362,391,420,419,418,417,416,415,414,413,412,411,410,409,408,407,406,377,348,319,290,261,232,203,174,145,116,87,58,29,15,16,17,18,19,20,21,22,23,24,25,26,27,28,57,86,115,144,173,202,231,260,289,318,347,376,405,404,403,402,401,400,399,398,397,396,395,394,393,392,363,334,305,276,247,218,189,160,131,102,73,44,30,31,32,33,34,35,36,37,38,39,40,41,42,71,100,129,158,187,216,245,274,303,332,361,390,389,388,387,386,385,384,383,382,381,380,379,378,349,320,291,262,233,204,175,146,117,88,59,45,46,47,48,49,50,51,52,53,54,55,56,85,114,143,172,201,230,259,288,317,346,375,374,373,372,371,370,369,368,367,366,365,364,335,306,277,248,219,190,161,132,103,74,60,61,62,63,64,65,66,67,68,69,70,99,128,157,186,215,244,273,302,331,360,359,358,357,356,355,354,353,352,351,350,321,292,263,234,205,176,147,118,89,75,76,77,78,79,80,81,82,83,84,113,142,171,200,229,258,287,316,345,344,343,342,341,340,339,338,337,336,307,278,249,220,191,162,133,104,90,91,92,93,94,95,96,97,98,127,156,185,214,243,272,301,330,329,328,327,326,325,324,323,322,293,264,235,206,177,148,119,105,106,107,108,109,110,111,112,141,170,199,228,257,286,315,314,313,312,311,310,309,308,279,250,221,192,163,134,120,121,122,123,124,125,126,155,184,213,242,271,300,299,298,297,296,295,294,265,236,207,178,149,135,136,137,138,139,140,169,198,227,256,285,284,283,282,281,280,251,222,193,164,150,151,152,153,154,183,212,241,270,269,268,267,266,237,208,179,165,166,167,168,197,226,255,254,253,252,223,194,180,181,182,211,240,239,238,209,195,196,225,224,210};   // circ
    #endif
  i = 0;  // used as max val
  for(n=0; n<N; n++) if(votes[n]>i) { i = votes[n];  j = n; }   // Qubit j has max vote
  bp->seq[0] = j;    i = 0;   // i is the index to read seq[i]
  for(n=1; n<N; n++) {
    if(seq[i]!=j) { bp->seq[n] = seq[i];    i++; }
    else          { bp->seq[n] = seq[i+1];  i+=2; }
  }
#else
  XXX_NOT_SUPPORT_XXX
#endif
}*/

#if MAJ_VOTE
//-- majority voting
static void maj_voting(QBP_Ctl *bp , GFQ_t *zz , a_matrix_GFQ *A , double p_ch) // inputs: follow Qbp_init20
{
  #if CH_TYPE==1 || ALFA_V!=0
  XXX_NOT_SUPPORT_YET_XXX
  #endif

  #if MAJ_VOTE == 1   // 1: vote by syndrome in maj_voting (tested, threshold j=1,2,3, not improved)
  int32_t  m , n , i , j , q ;
  int32_t voteI[N], voteX[N], voteZ[N], voteY[N] ,  vote_max[N], vote_idx[N];
  memset(voteI, 0, sizeof(voteI));  memset(voteX, 0, sizeof(voteX));  memset(voteZ, 0, sizeof(voteZ));  memset(voteY, 0, sizeof(voteY));

  for(m=0; m<M; m++)
  if(zz[m] == 0)  for(j=0; j < A->num_m[m]; j++) {
    n = A->mlist[m][j];
    q = A->mlist_val[m][j];       // {X,Z,Y} val {1,2,3}
    voteI[n]++;
    switch (q) {
    case 1: voteX[n]++; break;  // edge is X
    case 2: voteZ[n]++; break;  // edge is Z
    case 3: voteY[n]++; break;  // edge is Y
    default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
    }
  } // else zz[m] == 1:
  else  for(j=0; j < A->num_m[m]; j++) {
    n = A->mlist[m][j];
    q = A->mlist_val[m][j];       // {X,Z,Y} val {1,2,3}
    switch (q) {
    case 1: voteZ[n]++; voteY[n]++; break;  // edge is X
    case 2: voteX[n]++; voteY[n]++; break;  // edge is Z
    case 3: voteX[n]++; voteZ[n]++; break;  // edge is Y
    default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
    }
  }

  //-- init pn , by error type q (of I,X,Z,Y) with maximum vote
  /*j = 0;    // will count how many voted to be NOT I
  for(n=0; n<N; n++) {
    vote_max[n] = -1;
    if(voteI[n] > vote_max[n]) { vote_max[n] = voteI[n];  vote_idx[n] = 0; }
    if(voteX[n] > vote_max[n]) { vote_max[n] = voteX[n];  vote_idx[n] = 1; }
    if(voteZ[n] > vote_max[n]) { vote_max[n] = voteZ[n];  vote_idx[n] = 2; }
    if(voteY[n] > vote_max[n]) { vote_max[n] = voteY[n];  vote_idx[n] = 3; }

    //-- find which q to vote
    if(vote_max[n] >= 4)  { q = vote_idx[n];  }   // ONLY vote q when there 4 votes
    else                  { q = 0;            }   // DEF is to vote I
    //-- too many voted to be NOT I ?
    if(q!=0)  j++;
    if(j>1)   q=0;    // allow only 1 to be NOT I (if more than that, reset current q to I)
    //-- init pn
    bp->pn[n][q] = 1.0 - p_ch;
    for(i=1; i<Q; i++) bp->pn[n][(q+i)%Q] = p_ch/(Q-1);
  }*/
  //printf("j = %d \n", j);

  j = 0;    // will count how many voted to be NOT I
  for(n=0; n<N; n++) {
    vote_max[n] = -1;
    if(voteI[n] > vote_max[n]) { vote_max[n] = voteI[n];  vote_idx[n] = 0; }
    if(voteX[n] > vote_max[n]) { vote_max[n] = voteX[n];  vote_idx[n] = 1; }
    if(voteZ[n] > vote_max[n]) { vote_max[n] = voteZ[n];  vote_idx[n] = 2; }
    if(voteY[n] > vote_max[n]) { vote_max[n] = voteY[n];  vote_idx[n] = 3; }

    //-- find which q to vote
    if(vote_max[n] >= 4)  { q = vote_idx[n];  }   // ONLY vote q when there 4 votes
    else                  { q = 0;            }   // DEF is to vote I
    //-- how many voted to be NOT I ?
    if(q!=0)  j++;
  }
  //-- j has counted how many voted to be NOT I
  if(j<=1)  for(n=0; n<N; n++) {  // only do maj vote when j<=1 (be conservative)
    //-- find which q to vote
    if(vote_max[n] >= 4)  { q = vote_idx[n];  }   // ONLY vote q when there 4 votes
    else                  { q = 0;            }   // DEF is to vote I
    //-- init pn
    bp->pn[n][q] = 1.0 - p_ch;
    for(i=1; i<Q; i++) bp->pn[n][(q+i)%Q] = p_ch/(Q-1);
  }
  else  for(n=0; n<N; n++) {  // DEF to vote all as I
    bp->pn[n][0] = 1.0 - p_ch;
    for(q=1; q<Q; q++) bp->pn[n][q] = p_ch/(Q-1);
  }

  //-- init dqml[m][j] , according to the edge = X, Z, or Y
  for(m=0; m < A->MM; m++)
  for(j=0; j < A->num_m[m]; j++) {
    n = A->mlist[m][j];
    q = A->mlist_val[m][j];       // {X,Z,Y} val {1,2,3}
    bp->dqml[m][j] = 2*(bp->pn[n][0]+bp->pn[n][q]) - 1.0;
  }

  #elif MAJ_VOTE == 2   // 2: vote outer bits less reliable (need ORI=4115) (tested not good)
    #if ORI!=4115
    XXX_SUPPORT_XXX
    #endif

  //-- outer bits
  int32_t  m , n , j , q ;    double p_nos;
  for(n=0; n<=Surf_L*4; n++) {
    //p_nos = p_ch*2;
    //p_nos = p_ch*4;
    p_nos = 0.1;
    bp->pn[n][0] = 1.0 - p_nos;
    for(q=1; q<Q; q++) bp->pn[n][q] = p_nos/(Q-1);
  }
  //-- inner bits
  for(n=Surf_L*4+1; n<N; n++) {
    bp->pn[n][0] = 1.0 - p_ch;
    for(q=1; q<Q; q++) bp->pn[n][q] = p_ch/(Q-1);
  }
  //-- init dqml[m][j] , according to the edge = X, Z, or Y
  for(m=0; m < A->MM; m++)
  for(j=0; j < A->num_m[m]; j++) {
    n = A->mlist[m][j];
    q = A->mlist_val[m][j];       // {X,Z,Y} val {1,2,3}
    bp->dqml[m][j] = 2*(bp->pn[n][0]+bp->pn[n][q]) - 1.0;
  }
  #endif
}
#endif

#if MAJ_SCHE
static void maj_sche_init(QBP_Ctl *bp , GFQ_t *zz , a_matrix_GFQ *A)  // inputs: follow Qbp_init20
{
  int32_t m, j, n;
  memset(bp->maj_cnt, 0, sizeof(bp->maj_cnt));
  bp->maj_max = 0;

  for(m=0; m < A->MM; m++)
  if(zz[m])
  for(j=0; j < A->num_m[m]; j++) {
    n = A->mlist[m][j];

  #if MAJ_SCHE==1   // soft strategy
    bp->maj_cnt[n]++;
    if(bp->maj_cnt[n] > bp->maj_max)  bp->maj_max = bp->maj_cnt[n];

  #elif MAJ_SCHE==2 // hard strategy
    bp->maj_cnt[n] = 1;
    bp->maj_max = 1;

  #elif MAJ_SCHE==4 // hard, 2 times
    bp->maj_cnt[n] = 2;
    bp->maj_max = 2;

  #else
    XXX_NG_MAJ_SCHE_XXX
  #endif
  }

}
#endif


//-- "Quantum" BP init: set bp->tt as all zeros. return 1 if zz pass; otherwise INIT *bp and return 0
uint8_t Qbp_init20(QBP_Ctl *bp , GFQ_t *zz , a_matrix_GFQ *A , double p_ch, double afp) // zz: syndrome, p_ch: channel err rate, afp: see AFP
{
  int32_t  m , n , j, q;//// , i;
  double dn[N][Q-1];     // to buffer dn[n] = qn[n]^0 - qn[n]^1  for q be X,Z,Y

  //-- always reset output bp->tt as all zeros
  memset(bp->tt , 0 , sizeof(bp->tt));
//#if DBL_CHK
//  memset(bp->tt_last , 0 , sizeof(bp->tt_last));    // should rest in main(), not here
//#endif

  //-- return 1 if zz pass
  if( is_zero_vec(zz, M) )  return 1;
  //-- AFP init
  bp->ap = afp;

  //-- generate initial bias vector
  double init_p[Q], init_d[Q-1];  // init p_vec over {I,X,Z,Y} and (delta) d_vec over {X,Z,Y}
  GenInitBiasVec(init_p, init_d, p_ch);  // also apply CH_TYPE and ALFA_V insider

  //-- initial pn , dn
  for(n=0; n < A->NN; n++) {
    bp->pn[n][0] = init_p[0];
    for(q=1;q<Q;q++)  { bp->pn[n][q] = init_p[q];
                        dn[n][q-1]   = init_d[q-1]; }
  }

  //-- initial bp->qn   // can skip, as every iteration will init again
#if ITER_LOG  // may also enable if PARTIAL_UPD_BY_qn or DYNAMIC_pn
  memcpy ( bp->qn , bp->pn, sizeof(bp->qn) );
  ChkNode_GenSyndrome(A, bp);
#endif

  /*//-- init qlm[n][i] , according to the edge = X, Z, or Y
  for(n=0; n < A->NN; n++)
  for(i=0; i < A->num_n[n]; i++) {
    q = A->nlist_val[n][i] - 1;   // {X,Y,Z} val {1,2,3} -1 as idx {0,1,2}
    bp->qlm[n][i] = bp->pn[n][q];
  }*/     // not need as will pass by dqml

  //-- init dqml[m][j] , according to the edge = X, Z, or Y
  for(m=0; m < A->MM; m++)
  for(j=0; j < A->num_m[m]; j++) {
    n = A->mlist[m][j];
    q = A->mlist_val[m][j];       // {X,Z,Y} val {1,2,3}
    bp->dqml[m][j] = dn[n][q-1];  // q-1 as idx {0,1,2}
  }

#if EN_AFP_V  // init dqml_ori without applying ALFA_V
  for(q=1;q<Q;q++) {
    init_d[q-1] = 2*(init_p[0]+init_p[q]) - 1;  // reuse init_d, and recall init_p is without ALFA_V (refer GenInitBiasVec)
    if(fabs(init_d[q-1]) < 2*dlt) { printf("too small abs init_d[%d] %g , debug !!! \n", q-1, init_d[q-1]); getchar(); }
  }
  for(m=0; m < A->MM; m++)
  for(j=0; j < A->num_m[m]; j++) {
    q = A->mlist_val[m][j];       // {X,Z,Y} val {1,2,3}
    bp->dqml_ori[m][j] = init_d[q-1];  // q-1 as idx {0,1,2}
  }
#endif


  #if RND_SCHE == 2
  int32_t n1, tmp_n;   uint64_t seq_seed[4];   rnd256_init_priv(seq_seed);
  for(n=0; n<N-1; n++) {                  //-- cite https://danluu.com/sattolo/
    //n1 = priv_Nminus1(N, seq_seed);       // a discrete r.v. over {0, 1, 2, ..., N-1}   // Fisher-Yates approach (may multi-cycles)
    n1 = priv_IntAB(n+1, N-1, seq_seed);  // a discrete r.v. over {n+1,n+2, ..., N-1}   // Sattolo approach  (guaranteed one cycle)
    tmp_n = bp->seq[n];   bp->seq[n] = bp->seq[n1];   bp->seq[n1] = tmp_n;  // swap idxs at [n] and [n1]
  }
  #endif

  //-- special serial schedule
  //init_votes(bp , zz , A);
#if MAJ_VOTE
  maj_voting(bp , zz , A , p_ch);
#endif
#if MAJ_SCHE
  maj_sche_init(bp , zz , A);
#endif

  //-- set target syndrome
  memcpy ( bp->target_z , zz, sizeof(bp->target_z) );
  //-- INIT *bp done and return 0
  bp->reset = 1;  bp->iter = 0;   bp->is_hit_c = 0;
  return 0;
}


#if 0   // need to maintain ALFA_V and EN_AFP_V, or mark XXX_NOT_SUOOPRT_EN_ALFA_V_XXX below
//-- "Quantum" BP init WITH "Random Perturbation" (RAND_PERTURB) , based on Qbp_init20
uint8_t Qbp_init31(QBP_Ctl *bp , GFQ_t *zz , a_matrix_GFQ *A , double p_ch, double afp) // zz: syndrome, p_ch: channel err rate, afp: see AFP
{
  if(Q!=4)  { printf("Q=%u , but must =4 ! exit() !!", Q);  getchar();  exit(1); }

  int32_t  m , n , j, q;//// , i;
  double dn[N][Q-1];     // to buffer dn[n] = qn[n]^0 - qn[n]^1  for q be X,Z,Y
  double sum;

  //-- always reset output bp->tt as all zeros
  memset(bp->tt , 0 , sizeof(bp->tt));
  //-- return 1 if zz pass
  if( is_zero_vec(zz, M) )  return 1;
  //-- AFP init
  bp->ap = afp;

  //-- generate initial bias vector
  double init_p[Q], init_d[Q-1];  // init p_vec over {I,X,Z,Y} and (delta) d_vec over {X,Z,Y}
  GenInitBiasVec(init_p, init_d, p_ch);  // also apply CH_TYPE and ALFA_V insider

  //-- initial pn , dn
  for(n=0; n < A->NN; n++) {
    bp->pn[n][0] = init_p[0];
    for(q=1;q<Q;q++)  { bp->pn[n][q] = init_p[q];
                        dn[n][q-1]   = init_d[q-1]; }
  }
  //-- run RAND_PERTURB
#if ORI == 513
  #define B_PERTURB 3  // perturbed 4th qubit
  n = B_PERTURB;
  if(zz[0]==1 && zz[1]==1 && zz[2]==1 && zz[3]==1) {
    bp->pn[n][1]*= pow((1+0.5),2);  bp->pn[n][2]*= pow((1+0.5),2);  bp->pn[n][3]*= pow((1+0.5),4); // 2 X chks + 2 Z chks = 4 Y chks at qubit 4
  }
#elif ORI == 202
  #define B_PERTURB 0  // perturbed first qubit
  n = B_PERTURB;
  bp->pn[n][1]*= pow((1+0.5),1);  bp->pn[n][2]*= pow((1+0.5),0);  bp->pn[n][3]*= pow((1+0.5),0);
#elif ORI == 1115
  double eps = 0.0001;
  //==== X error
  //n = 9;  bp->pn[n][1]=1-eps;    bp->pn[n][0]=eps/3;    bp->pn[n][2]=eps/3;    bp->pn[n][3]=eps/3;
  //==== Z error
  //n = 6; bp->pn[n][2]=1-eps;    bp->pn[n][0]=eps/3;    bp->pn[n][1]=eps/3;    bp->pn[n][3]=eps/3;
  //==== Y errors
  n = 1;  bp->pn[n][3]=1-eps;    bp->pn[n][0]=eps/3;    bp->pn[n][1]=eps/3;    bp->pn[n][2]=eps/3;
  //n = 9;  bp->pn[n][3]=1-eps;    bp->pn[n][0]=eps/3;    bp->pn[n][1]=eps/3;    bp->pn[n][2]=eps/3;
  //==== XYZ errors
  //n = 1;  bp->pn[n][0]=eps;    bp->pn[n][1]=(1-eps)*3/6;  bp->pn[n][2]=(1-eps)*0/6;   bp->pn[n][3]=(1-eps)*3/6;
#else
  printf("RAND_PERTURB for this %u code not implemented yet !! Now to exit();  !! \n", ORI); getchar();  exit(1);
#endif

  sum=0;  for(q=0;q<Q;q++) { sum += bp->pn[n][q]; }         // compute sum after perturb
  for(q=0;q<Q;q++) { bp->pn[n][q] = bp->pn[n][q] / sum ; }  // do normalization
  dn[n][0] = (bp->pn[n][0]+bp->pn[n][1]) - (bp->pn[n][2]+bp->pn[n][3]);   // renew d=(pI+pX)/(pZ+pY) for X
  dn[n][1] = (bp->pn[n][0]+bp->pn[n][2]) - (bp->pn[n][1]+bp->pn[n][3]);   // renew d=(pI+pZ)/(pX+pY) for Z
  dn[n][2] = (bp->pn[n][0]+bp->pn[n][3]) - (bp->pn[n][1]+bp->pn[n][2]);   // renew d=(pI+pY)/(pX+pZ) for Y
#if ALFA_V || EN_AFP_V
  XXX_NOT_SUOOPRT_EN_ALFA_V_XXX
#endif

  //-- initial bp->qn   // can skip, as every iteration will init again
#if ITER_LOG  // may also enable if PARTIAL_UPD_BY_qn or DYNAMIC_pn
  memcpy ( bp->qn , bp->pn, sizeof(bp->qn) );
  ChkNode_GenSyndrome(A, bp);
#endif


  //-- init dqml[m][j] , according to the edge = X, Z, or Y
  for(m=0; m < A->MM; m++)
  for(j=0; j < A->num_m[m]; j++) {
    n = A->mlist[m][j];
    q = A->mlist_val[m][j];       // {X,Z,Y} val {1,2,3}
    bp->dqml[m][j] = dn[n][q-1];  // q-1 as idx {0,1,2}
  }


  #if RND_SCHE
  XXX_NOT_SUPPORT_XXX
  #endif

  //-- special serial schedule
  //init_votes(bp , zz , A);
#if MAJ_VOTE
  maj_voting(bp , zz , A , p_ch);
#endif
#if MAJ_SCHE
  maj_sche_init(bp , zz , A);
#endif

  //-- set target syndrome
  memcpy ( bp->target_z , zz, sizeof(bp->target_z) );
  //-- INIT *bp done and return 0
  bp->reset = 1;  bp->iter = 0;   bp->is_hit_c = 0;
  return 0;
}
#endif

static void HardDecision(QBP_Ctl *bp, a_matrix_GFQ *A)
{
  int32_t  n;

  //bp->iter += 1;  // always do this first
  // MOVED TO OUTSIDE (before calling this function)

#if POS_AVG==0
  for(n=0; n < A->NN; n++) {
    if(bp->qn[n][0] > bp->qn[n][1])
      if(bp->qn[n][2] > bp->qn[n][3])
      //if(bp->qn[n][2] >= bp->qn[n][3])       // prefer Z than Y
        if(bp->qn[n][0] > bp->qn[n][2]) bp->tt[n] = 0;  else  bp->tt[n] = 2;
      else
        if(bp->qn[n][0] > bp->qn[n][3]) bp->tt[n] = 0;  else  bp->tt[n] = 3;
    else  // [1] >= [0]
      if(bp->qn[n][2] > bp->qn[n][3])
        if(bp->qn[n][1] > bp->qn[n][2]) bp->tt[n] = 1;  else  bp->tt[n] = 2;
      else
        if(bp->qn[n][1] > bp->qn[n][3]) bp->tt[n] = 1;  else  bp->tt[n] = 3;
        //if(bp->qn[n][1] >= bp->qn[n][3]) bp->tt[n] = 1;  else  bp->tt[n] = 3;   // prefer X than Y
  }

#else //POS_AVG==1
  int32_t  base;
  double scal;

  //-- normalization
  for(n=0; n < N; n++) {
    scal = 1.0 / (bp->qn[n][0] + bp->qn[n][1] + bp->qn[n][2] + bp->qn[n][3]);
    bp->qn[n][0] *= scal;   bp->qn[n][1] *= scal;   bp->qn[n][2] *= scal;   bp->qn[n][3] *= scal;
  }

  //-- average
  if(bp->iter == 1)   memcpy(bp->qn_avg, bp->qn, sizeof(bp->qn_avg));
  else {
    if(bp->iter < POS_AVG) { base = bp->iter; }
    else                   { base = POS_AVG;  }
    for(n=0; n < N; n++) {
      bp->qn_avg[n][0] = (bp->qn_avg[n][0]*(base-1) + bp->qn[n][0]) / base;
      bp->qn_avg[n][1] = (bp->qn_avg[n][1]*(base-1) + bp->qn[n][1]) / base;
      bp->qn_avg[n][2] = (bp->qn_avg[n][2]*(base-1) + bp->qn[n][2]) / base;
      bp->qn_avg[n][3] = (bp->qn_avg[n][3]*(base-1) + bp->qn[n][3]) / base;
    }
  }

  //-- hard decision (by qn_avg, not qn)
  for(n=0; n < N; n++) {
    if(bp->qn_avg[n][0] > bp->qn_avg[n][1])
      if(bp->qn_avg[n][2] > bp->qn_avg[n][3])
      //if(bp->qn_avg[n][2] >= bp->qn_avg[n][3])       // prefer Z than Y
        if(bp->qn_avg[n][0] > bp->qn_avg[n][2]) bp->tt[n] = 0;  else  bp->tt[n] = 2;
      else
        if(bp->qn_avg[n][0] > bp->qn_avg[n][3]) bp->tt[n] = 0;  else  bp->tt[n] = 3;
    else  // [1] >= [0]
      if(bp->qn_avg[n][2] > bp->qn_avg[n][3])
        if(bp->qn_avg[n][1] > bp->qn_avg[n][2]) bp->tt[n] = 1;  else  bp->tt[n] = 2;
      else
        if(bp->qn_avg[n][1] > bp->qn_avg[n][3]) bp->tt[n] = 1;  else  bp->tt[n] = 3;
        //if(bp->qn_avg[n][1] >= bp->qn_avg[n][3]) bp->tt[n] = 1;  else  bp->tt[n] = 3;   // prefer X than Y
  }
#endif
}


/*#define DLT_L   (1e-12)         // need at least 1e-15 > 2^-52 (=2.22e-16) to let (1.0-DLT_L) not underflow.
#define DLT_U   (1.0 - DLT_L)   // to let (1.0+DLT_U)/2 not vanish to 2/2
#define restrict_d(d) \
{ \
  if (d > DLT_U)      { d = DLT_U; } \
  else if(d > -DLT_U) {  } \
  else                { d = -DLT_U; } \
}
#define restrict_d2(d) \
{ \
  if (d > DLT_U)      { d = DLT_U; } \
  else if(d > DLT_L)  {  } \
  else if(d > 0 )     { d = DLT_L; } \
  else if(d > -DLT_L) { d = -DLT_L; } \
  else if(d > -DLT_U) {  } \
  else                { d = -DLT_U; } \
}*/

//-- "Quantum" BP, serial update
uint8_t Qbp_dec24(QBP_Ctl *bp, a_matrix_GFQ *A)   // copy from bp_dec24 and modify
{
  int32_t  m, n, i, j, q, n2;
  double  rml_0, rml_1, qlm[2];//, dml;
/*
#if AFP
//#if AFP || AFP2
  double  ap = (double)100.0/AFP;
  ////if(bp->iter<100)    ap = 1.0;
  ////if(bp->iter>100)    ap = 1.0/1.2;
//  #if AFP2
//  if(bp->iter <= MAX_ITER/4)  ap = (double)100.0/AFP;
//  else                        ap = (double)100.0/AFP2;
//  #endif
  ////if(bp->iter<4)    ap = (double)100.0/(AFP + AFP2*bp->iter);
  ////else              ap = (double)100.0/(AFP + AFP2*4);
#endif
*/


  #if RND_SCHE == 3
  int32_t n1, tmp_n;   uint64_t seq_seed[4];   rnd256_init_priv(seq_seed);
  for(n=0; n<N-1; n++) {                  //-- cite https://danluu.com/sattolo/
    //n1 = priv_Nminus1(N, seq_seed);       // a discrete r.v. over {0, 1, 2, ..., N-1}   // Fisher-Yates approach (may multi-cycles)
    n1 = priv_IntAB(n+1, N-1, seq_seed);  // a discrete r.v. over {n+1,n+2, ..., N-1}   // Sattolo approach  (guaranteed one cycle)
    tmp_n = bp->seq[n];   bp->seq[n] = bp->seq[n1];   bp->seq[n1] = tmp_n;  // swap idxs at [n] and [n1]
  }
  #endif



 //if(bp->reset == 1) {
  //======== make all dm[M] ready first ========//
  for(m=0; m < A->MM; m++) {
    bp->dm[m] = (double)bp->target_z[m]*(-2) + 1;  // zm 0 -> 1,  zm 1 -> -1
    for(j=0; j < A->num_m[m]; j++) { bp->dm[m] *= bp->dqml[m][j]; }

    if(bp->dm[m]==0)  printf("\n\n hit bp->dm[m]==0 \n\n");   // HIT_ZERO_CHK
  }
 //}

  bp->reset = 0;


#if BETA_pn == 0    //######### CODE_DEFAULT #####################
  //-- init qn as pn
  memcpy ( bp->qn , bp->pn, sizeof(bp->qn) );           // CODE_DEFAULT
  //memcpy ( bp->qn , bp->pn, sizeof(bp->qn[0])*(N-K) );  // PARTIAL_UPD_BY_qn
#else
  for(n=0; n < A->NN; n++)
  for(q=0; q < Q; q++){
    bp->qn[n][q] = pow_fast(bp->pn[n][q], 100.0/BETA_pn) * pow_fast(bp->qn[n][q], 1.0 - 100.0/BETA_pn);
  }
#endif

  //======== main process of this iteration ========//
  //for(n=0; n < A->NN; n++) {  // ORI dec24

  for(n2=0; n2 < A->NN; n2++) { // FOR dec25 (also support dec24)
    n = bp->seq[n2];

  #if MAJ_SCHE
   if(bp->maj_cnt[n] == bp->maj_max){
  #endif

    for(i=0; i < A->num_n[n]; i++) {  // update n <- dml[m][j]
      m = A->nlist[n][i];
      j = A->ni2j[n][i];

      //if(bp->dqml[m][j]==0)  printf("\n\n hit bp->dqml[m][j]==0 \n\n");   // temp HIT_ZERO_CHK
    #if EN_AFP_V==0
      bp->dml[m][j] = bp->dm[m] / bp->dqml[m][j];
    #else
      bp->dml[m][j] = bp->dm[m] / bp->dqml_ori[m][j];
    #endif
      //if(bp->dml[m][j]==0)  printf("\n\n hit bp->dml[m][j]==0 \n\n");   // temp HIT_ZERO_CHK

    #if 0 // DEGEN_TEST
      //if     (bp->dml[m][j] >  0.9999999995)  bp->dml[m][j] =  0.9999999995;
      //else if(bp->dml[m][j] < -0.9999999995)  bp->dml[m][j] = -0.9999999995;
    #endif

    #if 1   // ORI: this is OK
      bp->rml[m][j][0] = (1.0+bp->dml[m][j])/2;   bp->rml[m][j][1] = (1.0-bp->dml[m][j])/2;   // MacKay r_ml^0 and r_ml^1
      //bp->rml[m][j][1] = 1.0 - bp->rml[m][j][0];
    #else   // RESTRICT_D: not needed
      dml = bp->dml[m][j];    restrict_d2(dml);
      bp->rml[m][j][0] = (1.0+dml)/2;
      bp->rml[m][j][1] = 1.0 - bp->rml[m][j][0];
    #endif

    #if BETA
      if     (bp->dml[m][j] >  DLT_BD)  { bp->rml[m][j][0] /= BETA; }
      else if(bp->dml[m][j] < -DLT_BD)  { bp->rml[m][j][1] /= BETA; }
      else                              { bp->rml[m][j][0]=1; bp->rml[m][j][1]=1;}
    #endif

    #if ALFA
      #if CYC_CHK
      bp->rml2[m][j][0] = bp->rml[m][j][0];   bp->rml2[m][j][1] = bp->rml[m][j][1];   // buffer rml before change
      #endif
      bp->rml[m][j][0] = pow_fast( bp->rml[m][j][0] , 100.0/ALFA );
      bp->rml[m][j][1] = pow_fast( bp->rml[m][j][1] , 100.0/ALFA );
    #endif
      rml_0 = bp->rml[m][j][0];   // shorthand notation
      rml_1 = bp->rml[m][j][1];

    #if GMN==0
      if(bp->ap!=0){  rml_0 = pow_fast( rml_0 , bp->ap );
                      rml_1 = pow_fast( rml_1 , bp->ap );
    #else
      double ap_used; static const double ap_bd = (double)LMN/100;
      if(bp->ap!=0){  if(A->num_m[m]>2) { ap_used = bp->ap; }
                      else              { ap_used = bp->ap*GMN/100;   if(ap_used > ap_bd) ap_used = ap_bd; }
                      rml_0 = pow_fast( rml_0 , ap_used );
                      rml_1 = pow_fast( rml_1 , ap_used );
    #endif
      #if CYC_CHK
        bp->rml2[m][j][0] = rml_0;   bp->rml2[m][j][1] = rml_1;   // buffer suppressed rm_0 and rml_l
      #endif
      }


      bp->qn[n][0] *= rml_0;  // update pI
      q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}
      switch (q) {
      case 1: bp->qn[n][1]*=rml_0;  bp->qn[n][2]*=rml_1;  bp->qn[n][3]*=rml_1;  break;  // edge is X
      case 2: bp->qn[n][1]*=rml_1;  bp->qn[n][2]*=rml_0;  bp->qn[n][3]*=rml_1;  break;  // edge is Z
      case 3: bp->qn[n][1]*=rml_1;  bp->qn[n][2]*=rml_1;  bp->qn[n][3]*=rml_0;  break;  // edge is Y
      default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
      }
      /*if(bp->qn[n][0]==0) printf("\n\n hit bp->qn[n][0]==0 \n\n");    // HIT_ZERO_CHK (default OFF here)
      if(bp->qn[n][1]==0) printf("\n\n hit bp->qn[n][1]==0 \n\n");
      if(bp->qn[n][2]==0) printf("\n\n hit bp->qn[n][2]==0 \n\n");
      if(bp->qn[n][3]==0) printf("\n\n hit bp->qn[n][3]==0 \n\n");*/
    }

    for(i=0; i < A->num_n[n]; i++) {  // update qlm[n][i] -> m  (by delta and m-friendly index dqml[m][j] -> m)
      m = A->nlist[n][i];
      j = A->ni2j[n][i];
      q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}
    #if AFPADD
      bp->rml[m][j][0] = pow_fast( bp->rml[m][j][0] , 1.0 + 100.0/AFPADD );
      bp->rml[m][j][1] = pow_fast( bp->rml[m][j][1] , 1.0 + 100.0/AFPADD );
    #endif

  #if CYC_CHK==0  // CODE_DEFAULT
      switch (q) {
      case 1: qlm[0]=(bp->qn[n][0]+bp->qn[n][1])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][2]+bp->qn[n][3])/bp->rml[m][j][1]; break;
      case 2: qlm[0]=(bp->qn[n][0]+bp->qn[n][2])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][1]+bp->qn[n][3])/bp->rml[m][j][1]; break;
      case 3: qlm[0]=(bp->qn[n][0]+bp->qn[n][3])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][1]+bp->qn[n][2])/bp->rml[m][j][1]; break;
      default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
      }
  #else // CYC_CHK
      double qn[Q];   memcpy(qn, bp->pn[n], sizeof(qn));
      int32_t i2, m2, j2, q2;

      for(i2=0; i2 < A->num_n[n]; i2++)
      if(i2 != i) {
        m2 = A->nlist[n][i2];
        j2 = A->ni2j[n][i2];

       if(ALFA)
        if(bp->cycs[n][i][i2]) { rml_0 = bp->rml[m2][j2][0];  rml_1 = bp->rml[m2][j2][1]; } // cycs > 0, use suppressed value
        else                   { rml_0 = bp->rml2[m2][j2][0]; rml_1 = bp->rml2[m2][j2][1];} // cycs = 0, use original value
       else if(bp->ap!=0)
        if(bp->cycs[n][i][i2]) { rml_0 = bp->rml2[m2][j2][0]; rml_1 = bp->rml2[m2][j2][1];} // cycs > 0, use suppressed value
        else                   { rml_0 = bp->rml[m2][j2][0];  rml_1 = bp->rml[m2][j2][1]; } // cycs = 0, use original value
        //{ rml_0 = pow_fast(bp->rml[m2][j2][0], 100.0/75);  rml_1 = pow_fast(bp->rml[m2][j2][1], 100.0/75); }  // if ap70 and here set to 100.0/75, then st file cyc_70_75_
       else { printf("must use ALFA or AFP for CYC_CHK !!  now to exit(); \n"); exit(1); }

        qn[0] *= rml_0;   // update pI
        q2 = A->mlist_val[m2][j2];  // {X,Z,Y} val {1,2,3}
        switch (q2) {
        case 1: qn[1]*=rml_0;  qn[2]*=rml_1;  qn[3]*=rml_1;  break;  // edge is X
        case 2: qn[1]*=rml_1;  qn[2]*=rml_0;  qn[3]*=rml_1;  break;  // edge is Z
        case 3: qn[1]*=rml_1;  qn[2]*=rml_1;  qn[3]*=rml_0;  break;  // edge is Y
        }
      }

      switch (q) {
      case 1: qlm[0]=(qn[0]+qn[1]); qlm[1]=(qn[2]+qn[3]); break;
      case 2: qlm[0]=(qn[0]+qn[2]); qlm[1]=(qn[1]+qn[3]); break;
      case 3: qlm[0]=(qn[0]+qn[3]); qlm[1]=(qn[1]+qn[2]); break;
      }

      if(bp->ap!=0) { qlm[0] /= pow_fast(bp->rml[m][j][0], 1.0 - bp->ap);
                      qlm[1] /= pow_fast(bp->rml[m][j][1], 1.0 - bp->ap); }
  #endif

    #if EN_AFP_V
      double qlm_ori[2];    qlm_ori[0] = qlm[0]/(qlm[0] + qlm[1]);    restrict_p2(qlm_ori);
      bp->dqml_ori[m][j] = qlm_ori[0] - qlm_ori[1];
    #endif
    #if ALFA_V
      qlm[0] = pow_fast( qlm[0] , 10.0/ALFA_V );  qlm[1] = pow_fast( qlm[1] , 10.0/ALFA_V );
    #endif
      //if(qlm[0]==0) printf("\n\n hit qlm[0]==0 \n\n");    // temp HIT_ZERO_CHK
      //if(qlm[1]==0) printf("\n\n hit qlm[1]==0 \n\n");

      //- normalizing qlm
      qlm[0] = qlm[0]/(qlm[0] + qlm[1]);    restrict_p2(qlm); // bound qlm[0] and gen qlm[1]
      //- update dqml
      bp->dqml[m][j] = qlm[0] - qlm[1];

      //- make dm more updated (KEY STEP for Serial BP)
      bp->dm[m] = bp->dml[m][j] * bp->dqml[m][j];

      //if(bp->dm[m]==0) printf("\n\n hit bp->dm[m]==0 \n\n");    // temp HIT_ZERO_CHK

    /*#if STOP_BY_C
      switch (q) {
      case 1: qlm[0]=(bp->qn[n][0]+bp->qn[n][1]); qlm[1]=(bp->qn[n][2]+bp->qn[n][3]); break;
      case 2: qlm[0]=(bp->qn[n][0]+bp->qn[n][2]); qlm[1]=(bp->qn[n][1]+bp->qn[n][3]); break;
      case 3: qlm[0]=(bp->qn[n][0]+bp->qn[n][3]); qlm[1]=(bp->qn[n][1]+bp->qn[n][2]); break;
      }
      qlm[0] = qlm[0]/(qlm[0] + qlm[1]);
      bp->dqml_c[m][j] = qlm[0]*2 - 1;
    #endif*/
    }
    //- normalizing qn
    // (can skip)

  #if MAJ_SCHE
    if(bp->maj_cnt[n]>0)  bp->maj_cnt[n] --;
   }
  #endif
  }
#if MAJ_SCHE
  if(bp->maj_max > 0)   bp->maj_max --;
#endif


  //======== hard decision ========//
  bp->iter += 1;  // always do this first
  HardDecision(bp, A);

  //======== Syndrome Checking ========//
//#if STOP_BY_C == 0
  Quan_GenSyndrome(A, bp->tt, bp->zz);
//#else
#if STOP_BY_C
  ChkNode_GenSyndrome(A, bp);
#endif


  //---- DYNAMIC_pn --------//
#if 0
  double qn_tmp[Q], llr_diff, diff_max = -1000, sum_p;
  int32_t max_n;
  for(n=0; n < A->NN; n++) {
    llr_diff = fabs( log2(bp->qn[n][0]/(bp->qn[n][1]+bp->qn[n][2]+bp->qn[n][3])) - log2(bp->pn[n][0]/(bp->pn[n][1]+bp->pn[n][2]+bp->pn[n][3])) );
    if(llr_diff > diff_max) { max_n = n;  diff_max = llr_diff; }
  }
  memcpy(qn_tmp, bp->qn[max_n], sizeof(qn_tmp));
  sum_p = qn_tmp[0]+qn_tmp[1]+qn_tmp[2]+qn_tmp[3];  qn_tmp[0]/=sum_p;  qn_tmp[1]/=sum_p;  qn_tmp[2]/=sum_p;  qn_tmp[3]/=sum_p;
  memcpy(bp->pn[max_n], qn_tmp, sizeof(qn_tmp));

  //n = max_n;              // DYNpn
  for(n=0; n < A->NN; n++)	// DYNpnALL
  for(i=0; i < A->num_n[n]; i++) {  // use qn to gen qlm, and update dqml
    m = A->nlist[n][i];
    j = A->ni2j[n][i];
    q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}
    switch (q) {
    case 1: bp->dqml[m][j] = (bp->pn[n][0]+bp->pn[n][1])*2 - 1; break;
    case 2: bp->dqml[m][j] = (bp->pn[n][0]+bp->pn[n][2])*2 - 1; break;
    case 3: bp->dqml[m][j] = (bp->pn[n][0]+bp->pn[n][3])*2 - 1; break;
    default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
    }
  }
  //return 0;
#endif


  //-- check if meet target_z
  if( 0 == HamDist(bp->zz, bp->target_z, A->MM) )  return 1;
  else                                             return 0;
}



uint8_t Qbp_dec20(QBP_Ctl *bp, a_matrix_GFQ *A)   // copy form Qbp_dec24 and modify
{
  int32_t  m, n, i, j, q;
  double  rml_0, rml_1, qlm[2];
/*#if AFP
  double  ap = (double)100.0/AFP;
  //if(bp->iter<100)    ap = 1.0;
  //if(bp->iter>100)    ap = 1.0/1.2;
  ////if(bp->iter <= MAX_ITER/2)  ap = (double)100.0/AFP;
  ////else                        ap = (double)100.0/AFP2;
  //if(bp->iter<4)    ap = (double)100.0/(AFP + AFP2*bp->iter);
  //else              ap = (double)100.0/(AFP + AFP2*4);
#endif*/

  //======== Horizontal Step ========//
  for(m=0; m < A->MM; m++) {
    bp->dm[m] = (double)bp->target_z[m]*(-2) + 1;  // zm 0 -> 1,  zm 1 -> -1
    for(j=0; j < A->num_m[m]; j++) { bp->dm[m] *= bp->dqml[m][j]; }   // make dm[m] init val ready first!!

    if(bp->dm[m]==0)  printf("\n\n hit bp->dm[m]==0 \n\n");

    for(j=0; j < A->num_m[m]; j++) {  // update every dml and rml
    #if EN_AFP_V==0
      bp->dml[m][j] = bp->dm[m] / bp->dqml[m][j];
    #else
      bp->dml[m][j] = bp->dm[m] / bp->dqml_ori[m][j];
    #endif

    #if 0 // DEGEN_TEST
      if     (bp->dml[m][j] >  0.9999995)  bp->dml[m][j] -= 0.0000005;
      else if(bp->dml[m][j] < -0.9999995)  bp->dml[m][j] += 0.0000005;
      //if     (bp->dml[m][j] >  0.05)  bp->dml[m][j] -= 0.05;
      //else if(bp->dml[m][j] < -0.05)  bp->dml[m][j] += 0.05;
    #endif

      //restrict_d2(bp->dml[m][j]);
      bp->rml[m][j][0] = (1.0+bp->dml[m][j])/2;   bp->rml[m][j][1] = (1.0-bp->dml[m][j])/2;   // MacKay r_ml^0 and r_ml^1
      //bp->rml[m][j][1] = 1.0 - bp->rml[m][j][0];
    }
  }

  bp->reset = 0;



  //======== Vertical Step (Update qn + Update qlm) ========//
#if BETA_pn == 0    //######### CODE_DEFAULT #####################
  //-- init qn as pn
  memcpy ( bp->qn , bp->pn, sizeof(bp->qn) );           // CODE_DEFAULT
  //memcpy ( bp->qn , bp->pn, sizeof(bp->qn[0])*(N-K) );  // PARTIAL_UPD_BY_qn
#else
  for(n=0; n < A->NN; n++)
  for(q=0; q < Q; q++){
    bp->qn[n][q] = pow_fast(bp->pn[n][q], 100.0/BETA_pn) * pow_fast(bp->qn[n][q], 1.0 - 100.0/BETA_pn);
  }
#endif


  //---- DYNAMIC_qn (only for test, not used) --------//
  //static double qn_tmp[Q];
  /*if(bp->iter == 1){
    memcpy(qn_tmp, bp->qn[3], sizeof(qn_tmp));
    memcpy ( bp->qn , bp->pn, sizeof(bp->qn) );
    memcpy(bp->qn[3], qn_tmp, sizeof(qn_tmp));
  }
  else if(bp->iter > 1){
    memcpy ( bp->qn , bp->pn, sizeof(bp->qn) );
    memcpy(bp->qn[3], qn_tmp, sizeof(qn_tmp));
  }*/

  //---- DYNAMIC_pn (ItGr0 or ItGr1) --------//
  /*double llr_diff, diff_max = -1000, sum_p;
  int32_t max_n;
  if(bp->iter >= 0){  // Iter Greater 0 or 1 (ItGr0 or ItGr1)
    for(n=0; n < A->NN; n++) {
      llr_diff = fabs( log2(bp->qn[n][0]/(bp->qn[n][1]+bp->qn[n][2]+bp->qn[n][3])) - log2(bp->pn[n][0]/(bp->pn[n][1]+bp->pn[n][2]+bp->pn[n][3])) );
      if(llr_diff > diff_max) { max_n = n;  diff_max = llr_diff; }
    }
    memcpy(qn_tmp, bp->qn[max_n], sizeof(qn_tmp));
    sum_p = qn_tmp[0]+qn_tmp[1]+qn_tmp[2]+qn_tmp[3];  qn_tmp[0]/=sum_p;  qn_tmp[1]/=sum_p;  qn_tmp[2]/=sum_p;  qn_tmp[3]/=sum_p;
    memcpy(bp->pn[max_n], qn_tmp, sizeof(qn_tmp));
    memcpy ( bp->qn , bp->pn, sizeof(bp->qn) );
  }*/


  //-- loop all variable nodes
  for(n=0; n < A->NN; n++) {

  #if MAJ_SCHE
   ////if(bp->maj_cnt[n] == bp->maj_max){
   XXX_NOT_SUPPORT_YEY_XXX
  #endif

    for(i=0; i < A->num_n[n]; i++) {  // update qn <- rml
      m = A->nlist[n][i];
      j = A->ni2j[n][i];

    #if BETA
      if     (bp->dml[m][j] >  DLT_BD)  { bp->rml[m][j][0] /= BETA; }
      else if(bp->dml[m][j] < -DLT_BD)  { bp->rml[m][j][1] /= BETA; }
      else                              { bp->rml[m][j][0]=1; bp->rml[m][j][1]=1;}
    #endif

    #if ALFA
      #if CYC_CHK
      bp->rml2[m][j][0] = bp->rml[m][j][0];   bp->rml2[m][j][1] = bp->rml[m][j][1];   // buffer rml before change
      #endif
      bp->rml[m][j][0] = pow_fast( bp->rml[m][j][0] , 100.0/ALFA );
      bp->rml[m][j][1] = pow_fast( bp->rml[m][j][1] , 100.0/ALFA );
    #endif
      rml_0 = bp->rml[m][j][0];   // shorthand notation
      rml_1 = bp->rml[m][j][1];

    #if GMN==0
      if(bp->ap!=0){  rml_0 = pow_fast( rml_0 , bp->ap );
                      rml_1 = pow_fast( rml_1 , bp->ap );
    #else
      double ap_used; static const double ap_bd = (double)LMN/100;
      if(bp->ap!=0){  if(A->num_m[m]>2) { ap_used = bp->ap; }
                      else              { ap_used = bp->ap*GMN/100;   if(ap_used > ap_bd) ap_used = ap_bd; }
                      rml_0 = pow_fast( rml_0 , ap_used );
                      rml_1 = pow_fast( rml_1 , ap_used );
    #endif
      #if CYC_CHK
        bp->rml2[m][j][0] = rml_0;   bp->rml2[m][j][1] = rml_1;   // buffer suppressed rm_0 and rml_l
      #endif
      }

      bp->qn[n][0] *= rml_0;  // update pI
      q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}
      switch (q) {
      case 1: bp->qn[n][1]*=rml_0;  bp->qn[n][2]*=rml_1;  bp->qn[n][3]*=rml_1;  break;  // edge is X
      case 2: bp->qn[n][1]*=rml_1;  bp->qn[n][2]*=rml_0;  bp->qn[n][3]*=rml_1;  break;  // edge is Z
      case 3: bp->qn[n][1]*=rml_1;  bp->qn[n][2]*=rml_1;  bp->qn[n][3]*=rml_0;  break;  // edge is Y
      default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
      }
      /*if(bp->qn[n][0]==0) printf("\n\n hit bp->qn[n][0]==0 \n\n");
      if(bp->qn[n][1]==0) printf("\n\n hit bp->qn[n][1]==0 \n\n");
      if(bp->qn[n][2]==0) printf("\n\n hit bp->qn[n][2]==0 \n\n");
      if(bp->qn[n][3]==0) printf("\n\n hit bp->qn[n][2]==0 \n\n");*/
    }
  }
  //======== Vertical Step (Update qn done) ========//

  //-------- hard decision --------//
  bp->iter += 1;  // always do this first
  HardDecision(bp, A);

  //-------- Syndrome Checking --------//
//#if STOP_BY_C == 0
  Quan_GenSyndrome(A, bp->tt, bp->zz);
//#else
#if STOP_BY_C
  ChkNode_GenSyndrome(A, bp);
#endif

  //-- check if meet target_z
  if(0 == HamDist(bp->zz, bp->target_z, A->MM)) { return 1; }
  else if(bp->iter == MAX_ITER)                 { return 0; }
  else                                          { } // DELAY_RETURN_0 since need to update qlm



  //======== Vertical Step (cont. to Update qlm) ========//
  for(n=0; n < A->NN; n++) {

    for(i=0; i < A->num_n[n]; i++) {  // use qn to gen qlm, and update dqml
      m = A->nlist[n][i];
      j = A->ni2j[n][i];
      q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}
    #if AFPADD
      bp->rml[m][j][0] = pow_fast( bp->rml[m][j][0] , 1.0 + 100.0/AFPADD );
      bp->rml[m][j][1] = pow_fast( bp->rml[m][j][1] , 1.0 + 100.0/AFPADD );
    #endif

  #if CYC_CHK==0  // CODE_DEFAULT
      switch (q) {
      case 1: qlm[0]=(bp->qn[n][0]+bp->qn[n][1])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][2]+bp->qn[n][3])/bp->rml[m][j][1]; break;
      case 2: qlm[0]=(bp->qn[n][0]+bp->qn[n][2])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][1]+bp->qn[n][3])/bp->rml[m][j][1]; break;
      case 3: qlm[0]=(bp->qn[n][0]+bp->qn[n][3])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][1]+bp->qn[n][2])/bp->rml[m][j][1]; break;
      default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
      }
  #else // CYC_CHK
      double qn[Q];   memcpy(qn, bp->pn[n], sizeof(qn));
      int32_t i2, m2, j2, q2;

      for(i2=0; i2 < A->num_n[n]; i2++)
      if(i2 != i) {
        m2 = A->nlist[n][i2];
        j2 = A->ni2j[n][i2];

       if(ALFA)
        if(bp->cycs[n][i][i2]) { rml_0 = bp->rml[m2][j2][0];  rml_1 = bp->rml[m2][j2][1]; } // cycs > 0, use suppressed value
        else                   { rml_0 = bp->rml2[m2][j2][0]; rml_1 = bp->rml2[m2][j2][1];} // cycs = 0, use original value
       else if(bp->ap!=0)
        if(bp->cycs[n][i][i2]) { rml_0 = bp->rml2[m2][j2][0]; rml_1 = bp->rml2[m2][j2][1];} // cycs > 0, use suppressed value
        else                   { rml_0 = bp->rml[m2][j2][0];  rml_1 = bp->rml[m2][j2][1]; } // cycs = 0, use original value
       else { printf("must use ALFA or AFP for CYC_CHK !!  now to exit(); \n"); exit(1); }

        qn[0] *= rml_0;   // update pI
        q2 = A->mlist_val[m2][j2];  // {X,Z,Y} val {1,2,3}
        switch (q2) {
        case 1: qn[1]*=rml_0;  qn[2]*=rml_1;  qn[3]*=rml_1;  break;  // edge is X
        case 2: qn[1]*=rml_1;  qn[2]*=rml_0;  qn[3]*=rml_1;  break;  // edge is Z
        case 3: qn[1]*=rml_1;  qn[2]*=rml_1;  qn[3]*=rml_0;  break;  // edge is Y
        }
      }

      switch (q) {
      case 1: qlm[0]=(qn[0]+qn[1]); qlm[1]=(qn[2]+qn[3]); break;
      case 2: qlm[0]=(qn[0]+qn[2]); qlm[1]=(qn[1]+qn[3]); break;
      case 3: qlm[0]=(qn[0]+qn[3]); qlm[1]=(qn[1]+qn[2]); break;
      }

      if(bp->ap!=0) { qlm[0] /= pow_fast(bp->rml[m][j][0], 1.0 - bp->ap);
                      qlm[1] /= pow_fast(bp->rml[m][j][1], 1.0 - bp->ap); }
  #endif

    #if EN_AFP_V
      double qlm_ori[2];    qlm_ori[0] = qlm[0]/(qlm[0] + qlm[1]);    restrict_p2(qlm_ori);
      bp->dqml_ori[m][j] = qlm_ori[0] - qlm_ori[1];
    #endif
    #if ALFA_V
      qlm[0] = pow_fast( qlm[0] , 10.0/ALFA_V );  qlm[1] = pow_fast( qlm[1] , 10.0/ALFA_V );
    #endif
      //- normalizing qlm
      qlm[0] = qlm[0]/(qlm[0] + qlm[1]);    restrict_p2(qlm); // bound qlm[0] and gen qlm[1]
      //- update dqml
      bp->dqml[m][j] = qlm[0] - qlm[1];

    /*#if STOP_BY_C
      switch (q) {
      case 1: qlm[0]=(bp->qn[n][0]+bp->qn[n][1]); qlm[1]=(bp->qn[n][2]+bp->qn[n][3]); break;
      case 2: qlm[0]=(bp->qn[n][0]+bp->qn[n][2]); qlm[1]=(bp->qn[n][1]+bp->qn[n][3]); break;
      case 3: qlm[0]=(bp->qn[n][0]+bp->qn[n][3]); qlm[1]=(bp->qn[n][1]+bp->qn[n][2]); break;
      }
      qlm[0] = qlm[0]/(qlm[0] + qlm[1]);
      bp->dqml_c[m][j] = qlm[0]*2 - 1;
    #endif*/
    }
    //- normalizing qn
    // (can skip)

  #if MAJ_SCHE
    ////if(bp->maj_cnt[n]>0)  bp->maj_cnt[n] --;
   ////}
   XXX_NOT_SUPPORT_YEY_XXX
  #endif
  }
#if MAJ_SCHE
  ////if(bp->maj_max > 0)   bp->maj_max --;
  XXX_NOT_SUPPORT_YEY_XXX
#endif


  //---- DYNAMIC_pn --------//
#if 0
  double qn_tmp[Q], llr_diff, diff_max = -1000, sum_p;
  int32_t max_n;
  for(n=0; n < A->NN; n++) {
    llr_diff = fabs( log2(bp->qn[n][0]/(bp->qn[n][1]+bp->qn[n][2]+bp->qn[n][3])) - log2(bp->pn[n][0]/(bp->pn[n][1]+bp->pn[n][2]+bp->pn[n][3])) );
    //llr_diff = pow(log2(bp->qn[n][0]/bp->qn[n][1])-log2(bp->pn[n][0]/bp->pn[n][1]), 2) + pow(log2(bp->qn[n][0]/bp->qn[n][2])-log2(bp->pn[n][0]/bp->pn[n][2]), 2) + pow(log2(bp->qn[n][0]/bp->qn[n][3])-log2(bp->pn[n][0]/bp->pn[n][3]), 2);
      // this is for DYNpnALL4 (bad performance)
    if(llr_diff > diff_max) { max_n = n;  diff_max = llr_diff; }
  }
  memcpy(qn_tmp, bp->qn[max_n], sizeof(qn_tmp));
  sum_p = qn_tmp[0]+qn_tmp[1]+qn_tmp[2]+qn_tmp[3];  qn_tmp[0]/=sum_p;  qn_tmp[1]/=sum_p;  qn_tmp[2]/=sum_p;  qn_tmp[3]/=sum_p;
  memcpy(bp->pn[max_n], qn_tmp, sizeof(qn_tmp));

  //n = max_n;              // DYNpn
  for(n=0; n < A->NN; n++)  // DYNpnALL
  for(i=0; i < A->num_n[n]; i++) {  // use qn to gen qlm, and update dqml
    m = A->nlist[n][i];
    j = A->ni2j[n][i];
    q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}
    switch (q) {
    case 1: bp->dqml[m][j] = (bp->pn[n][0]+bp->pn[n][1])*2 - 1; break;
    case 2: bp->dqml[m][j] = (bp->pn[n][0]+bp->pn[n][2])*2 - 1; break;
    case 3: bp->dqml[m][j] = (bp->pn[n][0]+bp->pn[n][3])*2 - 1; break;
    default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
    }
  }
  //return 0;
#endif


  return 0;   // do the DELAY_RETURN_0 now
}




//-- "Quantum" BP, serial update (along check nodes)
uint8_t Qbp_dec44(QBP_Ctl *bp, a_matrix_GFQ *A)   // copy form Qbp_dec20 and modify
{
  int32_t  m, n, j, q; //i;
  double  rml_0, rml_1, qlm[2];
/*#if AFP
  double  ap = (double)100.0/AFP;
#endif*/

  if(bp->reset == 1) { // init qn and default rml
  #if BETA_pn == 0    //######### CODE_DEFAULT #####################
    //-- init qn as pn
    memcpy ( bp->qn , bp->pn, sizeof(bp->qn) );           // CODE_DEFAULT
    //memcpy ( bp->qn , bp->pn, sizeof(bp->qn[0])*(N-K) );  // PARTIAL_UPD_BY_qn
  #else
    for(n=0; n < A->NN; n++)
    for(q=0; q < Q; q++){
      bp->qn[n][q] = pow_fast(bp->pn[n][q], 100.0/BETA_pn) * pow_fast(bp->qn[n][q], 1.0 - 100.0/BETA_pn);
    }
  #endif

  #if 1
    for(n=0; n < A->NN; n++)
    for(q=0; q < Q; q++){  bp->qn[n][q] *= pow(2.0, 512);  }  // raise to about log2(10^(308/2)), can increase the precision and should be no harm to the algorithm
  #endif

    for(m=0; m < A->MM; m++) for(j=0; j < A->num_m[m]; j++) { bp->rml[m][j][0] = 1.0;   bp->rml[m][j][1] = 1.0; }
  }
  bp->reset = 0;

  //-- refresh qn
  // skip first, as need more memories to handle AFP

  //================ serial update along check nodes ================//
  for(m=0; m < A->MM; m++) {
    bp->dm[m] = (double)bp->target_z[m]*(-2) + 1;  // zm 0 -> 1,  zm 1 -> -1
    //-------- pull dqml and update dm --------// (rml already ready)
    for(j=0; j < A->num_m[m]; j++) {
      n = A->mlist[m][j];
      q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}
    #if AFPADD
      XXX_NOT_SUPPORT_XXX
    #endif
      /*switch (q) {
      case 1: qlm[0]=(bp->qn[n][0]+bp->qn[n][1])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][2]+bp->qn[n][3])/bp->rml[m][j][1]; break;
      case 2: qlm[0]=(bp->qn[n][0]+bp->qn[n][2])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][1]+bp->qn[n][3])/bp->rml[m][j][1]; break;
      case 3: qlm[0]=(bp->qn[n][0]+bp->qn[n][3])/bp->rml[m][j][0]; qlm[1]=(bp->qn[n][1]+bp->qn[n][2])/bp->rml[m][j][1]; break;
      default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
      }*/
      rml_0 = bp->rml[m][j][0];   rml_1 = bp->rml[m][j][1];   // shorthand notation
      switch (q) {
      case 1: bp->qn[n][0]/=rml_0;  bp->qn[n][1]/=rml_0;      qlm[0] = bp->qn[n][0]+bp->qn[n][1];
              bp->qn[n][2]/=rml_1;  bp->qn[n][3]/=rml_1;      qlm[1] = bp->qn[n][2]+bp->qn[n][3];   break;
      case 2: bp->qn[n][0]/=rml_0;  bp->qn[n][2]/=rml_0;      qlm[0] = bp->qn[n][0]+bp->qn[n][2];
              bp->qn[n][1]/=rml_1;  bp->qn[n][3]/=rml_1;      qlm[1] = bp->qn[n][1]+bp->qn[n][3];   break;
      case 3: bp->qn[n][0]/=rml_0;  bp->qn[n][3]/=rml_0;      qlm[0] = bp->qn[n][0]+bp->qn[n][3];
              bp->qn[n][1]/=rml_1;  bp->qn[n][2]/=rml_1;      qlm[1] = bp->qn[n][1]+bp->qn[n][2];   break;
      default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
      }
    #if EN_AFP_V
      double qlm_ori[2];    qlm_ori[0] = qlm[0]/(qlm[0] + qlm[1]);    restrict_p2(qlm_ori);
      bp->dqml_ori[m][j] = qlm_ori[0] - qlm_ori[1];
    #endif
    #if ALFA_V
      qlm[0] = pow_fast( qlm[0] , 10.0/ALFA_V );  qlm[1] = pow_fast( qlm[1] , 10.0/ALFA_V );
    #endif
      //- normalizing qlm
      qlm[0] = qlm[0]/(qlm[0] + qlm[1]);    restrict_p2(qlm); // bound qlm[0] and gen qlm[1]
      //- update dqml
      bp->dqml[m][j] = qlm[0] - qlm[1];   //// dqml more updated if qn more updated

    #if STOP_BY_C
      //XXX_NOT_SUPPORT_XXX
    #endif

      bp->dm[m] *= bp->dqml[m][j];    //////// UPDATING dm HERE !!!! ////////////////
    }
    if(bp->dm[m]==0)  printf("\n\n hit bp->dm[m]==0 \n\n");

    //-------- dispatch dml --------//  //// and make qn more updated
    for(j=0; j < A->num_m[m]; j++) {
    #if EN_AFP_V==0
      bp->dml[m][j] = bp->dm[m] / bp->dqml[m][j];
    #else
      bp->dml[m][j] = bp->dm[m] / bp->dqml_ori[m][j];
    #endif
      bp->rml[m][j][0] = (1.0+bp->dml[m][j])/2;   bp->rml[m][j][1] = (1.0-bp->dml[m][j])/2;   // MacKay r_ml^0 and r_ml^1
      //bp->rml[m][j][1] = 1.0 - bp->rml[m][j][0];

    #if BETA
      XXX_NOT_SUPPORT_XXX
    #endif

    #if ALFA
      bp->rml[m][j][0] = pow_fast( bp->rml[m][j][0] , 100.0/ALFA );
      bp->rml[m][j][1] = pow_fast( bp->rml[m][j][1] , 100.0/ALFA );
    #endif
      rml_0 = bp->rml[m][j][0];   // shorthand notation
      rml_1 = bp->rml[m][j][1];
    /*#if AFP
      rml_0 = pow_fast( rml_0 , ap );
      rml_1 = pow_fast( rml_1 , ap );
    #endif*/
    #if GMN==0
      if(bp->ap!=0){  rml_0 = pow_fast( rml_0 , bp->ap );
                      rml_1 = pow_fast( rml_1 , bp->ap ); }
    #else
      double ap_used; static const double ap_bd = (double)LMN/100;
      if(bp->ap!=0) { if(A->num_m[m]>2) { ap_used = bp->ap; }
                      else              { ap_used = bp->ap*GMN/100;   if(ap_used > ap_bd) ap_used = ap_bd; }
                      rml_0 = pow_fast( rml_0 , ap_used );
                      rml_1 = pow_fast( rml_1 , ap_used );
                    }
    #endif

      n = A->mlist[m][j];
      bp->qn[n][0] *= rml_0;  // update pI
      q = A->mlist_val[m][j]; // {X,Z,Y} val {1,2,3}
      switch (q) {
      case 1: bp->qn[n][1]*=rml_0;  bp->qn[n][2]*=rml_1;  bp->qn[n][3]*=rml_1;  break;  // edge is X
      case 2: bp->qn[n][1]*=rml_1;  bp->qn[n][2]*=rml_0;  bp->qn[n][3]*=rml_1;  break;  // edge is Z
      case 3: bp->qn[n][1]*=rml_1;  bp->qn[n][2]*=rml_1;  bp->qn[n][3]*=rml_0;  break;  // edge is Y
      default:  printf("NG q = %u , must debug, suggest CTRL-C to exit;\n", q); getchar();
      }
    } //-------- dispatch to each dml --------// DONE
  } //======== END OF "serial update along check nodes" ========//


  //======== hard decision ========//
  bp->iter += 1;  // always do this first
  HardDecision(bp, A);

  //======== Syndrome Checking ========//
//#if STOP_BY_C == 0
  Quan_GenSyndrome(A, bp->tt, bp->zz);
//#else
#if STOP_BY_C
  //XXX_NOT_SUPPORT_XXX
  ChkNode_GenSyndrome(A, bp);
#endif

  //-- check if meet target_z
  if( 0 == HamDist(bp->zz, bp->target_z, A->MM) )  return 1;
  else                                             return 0;

}


#if USE_GF2_DEC
//-- load sparse from file to a_matrix *A
void load_A2(FILE *fpA, a2_matrix *A)
{
const int dbg_prt=0;

  int32_t err, val;
  int32_t m, n, i, j;

  //---- load A, see comments below
  err = fscanf(fpA, "%d %d %d %d", &(A->NN), &(A->MM), &(A->max_num_n), &(A->max_num_m));
  if(err==EOF) { printf("scan A basic parm NG !!\n");  exit(1); }
  printf("A2->[NN,MM,max_num_n,max_num_m] = [%d %d %d %d] \n", A->NN, A->MM, A->max_num_n, A->max_num_m);

  if(dbg_prt) printf(" num_n = ");
  for(n = 0 ; n < A->NN; n++) {
    err = fscanf(fpA, "%d", &(A->num_n[n]));
    if(dbg_prt) printf("%d ", A->num_n[n]);
  }
  if(err==EOF) { printf("scan A num_n NG !!\n");  exit(1); }

  if(dbg_prt) printf("\n num_m = ");
  for(m = 0 ; m < A->MM; m++) {
    err = fscanf(fpA, "%d", &(A->num_m[m]));
    if(dbg_prt) printf("%d ", A->num_m[m]);
  }
  if(err==EOF) { printf("scan A num_m NG !!\n");  exit(1); }

  printf("\n");
  for(n=0 ; n < A->NN; n++) {
    A->nlist[n] = (int32_t*)calloc(A->num_n[n] , sizeof( *(A->nlist[n]) ) );
    for(i=0 ; i < A->num_n[n]; i++) {
      err = fscanf( fpA , "%d" , &val );  A->nlist[n][i]=val-1;
      if(dbg_prt)  printf( "%d @%p  " , A->nlist[n][i] , &(A->nlist[n][i]) );
    }
    if(dbg_prt) printf( "  from A->nlist[%d] %p  @%p \n" , n , A->nlist[n] , &(A->nlist[n]) );

    for( ; i < A->max_num_n; i++)  err = fscanf(fpA, "%d", &val);   // read out dummy
    if(err==EOF) { printf("scan A nlist[%d] NG !!\n", n);  exit(1); }
  }

  for(m = 0 ; m < A->MM; m++) {
    A->mlist[m] = (int32_t*)calloc(A->num_m[m] , sizeof( *(A->mlist[m]) ) );
    for(j=0 ; j < A->num_m[m]; j++) {
      err = fscanf( fpA , "%d" , &val );  A->mlist[m][j]=val-1;
      if(dbg_prt)  printf( "%d @%p  " , A->mlist[m][j] , &(A->mlist[m][j]) );
    }
    if(dbg_prt) printf( "  from A->mlist[%d] %p  @%p \n" , m , A->mlist[m] , &(A->mlist[m]) );

    for( ; j < A->max_num_m; j++)  err = fscanf(fpA, "%d", &val);   // read out dummy
    if(err==EOF) { printf("scan A mlist[%d] NG !!\n", m);  exit(1); }
  }
/* (By convention, the righthand M*M submatrix is an invertible matrix)
a_matrix *A to
[1 1 0 1;
 0 0 1 1;
 1 1 1 1]
will have N=4; M=3,
  *num_n = [2 2 2 3], max_num_n = 3,
  *num_m = [3 2 4], max_num_m = 4,
  *nlist = [c1 c2 c3 c4] with *c1=[1 3 0], *r2=[1 3 0], *r3=[2 3 0], *r4=[1 2 3] all -1;
  *mlist = [r1 r2 r3] with *r1=[1 2 4 0], *r2=[3 4 0 0], *r1=[1 2 3 4] all -1;
  *ni2j = [j1 j2 j3 j4] with *j1=[0 0], *j2=[1 1], *j3=[0 2], *j4=[2 1 3];
          j1 means in col_1 the two ones has idx 0 and 0 in row order
*/
  err = fscanf(fpA, "%d", &val);
  if(err==EOF)  printf("load A done and success!\n");
  else        { printf("load A done but not hit EOF , NG !!\n");  exit(1); }

  if(A->NN != 2*N || A->MM != M) { printf("A2->[NN,MM] not match main [2N,M] !!\n");  exit(1); }
  //printf("press enter to continue...\n"); getchar();

  //====================================================
  //-- construct ni2j
  int32_t LM[M];  memset(LM, 0, M*sizeof(int32_t));
  for(n=0 ; n < A->NN; n++) {
    A->ni2j[n] = (int32_t*)calloc(A->num_n[n] , sizeof( *(A->ni2j[n]) ) );
    for(i=0 ; i < A->num_n[n]; i++) {
      m = A->nlist[n][i];
      A->ni2j[n][i] = LM[m];    LM[m]++;
      if(dbg_prt)  printf("%d ", A->ni2j[n][i]);
    }
    if(dbg_prt) printf(" in ni2j[%d]\n", n);
  }
  //printf("press enter to continue...\n"); getchar();
}


//-- alloc for BP2 Ctrl Blk
void alloc_BPC2(a2_matrix *A, BP2_Ctl *bp)
{
  int32_t  m , n;
  for(m=0; m < A->MM; m++) {
    bp->dml[m] = (double*)calloc(A->num_m[m], sizeof( *(bp->dml[m]) ) );
    bp->rml[m] = (double (*)[2])calloc(A->num_m[m]*2, sizeof( **(bp->rml[m]) ) );
    bp->dqml[m] = (double*)calloc(A->num_m[m], sizeof( *(bp->dqml[m]) ) );

    /*for(n=0; n < A->num_m[m]; n++)
      printf("%g %g  @%p %p  ", bp->rml[m][n][0], bp->rml[m][n][1], &(bp->rml[m][n][0]), &(bp->rml[m][n][1]) );
    printf("  of rml[%d] %p  @%p \n", m, bp->rml[m], &(bp->rml[m]));*/
  }

  for(n=0; n < A->NN; n++) {
    bp->qlm[n] = (double (*)[2])calloc(A->num_n[n]*2, sizeof( **(bp->qlm[n]) ) );
    //bp->dlm[n] = calloc(A->num_n[n], sizeof( *(bp->dlm[n]) ) );

    /*for(m=0; m < A->num_n[n]; m++)
      printf("%g %g  @%p %p  ", bp->qlm[n][m][0], bp->qlm[n][m][1], &(bp->qlm[n][m][0]), &(bp->qlm[n][m][1]) );
    printf("  of qlm[%d] %p  @%p \n", n, bp->qlm[n], &(bp->qlm[n]));*/
  }
  //getchar();
}


#if 0
//-- BP init and gen syndrome: bias => A->tt => syndrome chk => return 1 if pass; otherwise init bp and return 0
// mode = 'b'ias vec or 's'yndrome decoding
// when syndrome decoding, will use p_ch to init all pn[N]
uint8_t bp2_init20(BP2_Ctl *bp, double bias[][2], a2_matrix *A, uint8_t mode)
{
  int32_t  m , n , j;
  double dn[2*N];     // to buffer dn[n] = qn[n][0] - qn[n][1]
  double pn_afv[2];

  //-- init syndrome chk
  for(n=0; n < A->NN; n++) {
    if(bias[n][0] > 0.5)    bp->tt[n] = 0;
    else                    bp->tt[n] = 1;
  }
  GenSyndrome2(A, bp->tt, bp->zz);
  if(mode=='s') memset(bp->tt, 0, sizeof(bp->tt));  // before return, will set all bp->tt[n]=0 if mode=='s'
  if( is_zero_vec(bp->zz, A->MM) )  return 1;

  //-- either mode = 'b'ias vec or 's'yndrome decoding
  if(mode == 'b') goto BIAS_VEC_DEC;
  else            goto SYNDROME_DEC;

  //-- prepare to sun 's'yndrome decoding:
SYNDROME_DEC:
  memcpy ( bp->target_z , bp->zz, A->MM*sizeof(bp->target_z[0]) );
  for(n=0; n < A->NN; n++) { bp->pn[n][0] = 1.0 - bp->p_ch;     bp->pn[n][1] = bp->p_ch; }
  goto COMMON_PART;

  //-- Initialization Step of MacKay's '99 IT paper
BIAS_VEC_DEC:
  memset( bp->target_z , 0 , A->MM*sizeof(bp->target_z[0]) );
  memcpy ( bp->pn , bias, A->NN*2*sizeof(**bias) );
  goto COMMON_PART;

COMMON_PART:
  for(n=0; n < A->NN; n++) {
    restrict_p2(bp->pn[n]);  // make every pn[n] range restricted

    /*dn[n] = bp->pn[n][0] - bp->pn[n][1];  // gen delta = p0 - p1
    if(fabs(dn[n]) < 2*dlt) { printf("get too small abs from bp->dn[%d] %g , need debug !!! \n", n, dn[n]); getchar(); }

    for(j=0; j < A->num_n[n]; j++) {
      memcpy( bp->qlm[n][j] , bp->pn[n] , 2*sizeof(**bias) ); // bp->qlm[n][j][0]=bp->pn[n][0]; bp->qlm[n][j][1]=bp->pn[n][1];
    }*/

    pn_afv[0] = bp->pn[n][0];   pn_afv[1] = bp->pn[n][1];
  #if ALFA_V
    pn_afv[0] = pow_fast( pn_afv[0] , 10.0/ALFA_V );  pn_afv[1] = pow_fast( pn_afv[1] , 10.0/ALFA_V );
    pn_afv[0] = pn_afv[0]/(pn_afv[0] + pn_afv[1]);    restrict_p2(pn_afv);   // bound pn_afv[0] and gen pn_afv[1]
  #endif
    dn[n] = pn_afv[0] - pn_afv[1];
    if(fabs(dn[n]) < 2*dlt) { printf("too small abs dn[%d] %g , debug !!! \n", n, dn[n]); getchar(); }

    for(j=0; j < A->num_n[n]; j++) {
      memcpy( bp->qlm[n][j] , pn_afv , 2*sizeof(**bias) ); // bp->qlm[n][j][0]=bp->pn[n][0]; bp->qlm[n][j][1]=bp->pn[n][1];
    }
  }
  memcpy ( bp->qn , bp->pn, A->NN*2*sizeof(**bias) );

  for(m=0; m < A->MM; m++) {  // init all dqml[M][j] for 0 <= j < num_m[m]
    for(j=0; j < A->num_m[m]; j++) {
      n = A->mlist[m][j];
      bp->dqml[m][j] = dn[n];
    }
  }
  return 0;
}
#endif


//-- BP init and gen syndrome: bias => A->tt => syndrome chk => return 1 if pass; otherwise init bp and return 0
uint8_t bp2_init22(BP2_Ctl *bp, double bias[][2], a2_matrix *A, uint8_t *target_zz)
{
  int32_t  m , n , j;
  double dn[2*N];     // to buffer dn[n] = qn[n][0] - qn[n][1]
  double pn_afv[2];

  //-- init bp->target_z
  memcpy ( bp->target_z , target_zz, sizeof(bp->target_z) );

  //-- init syndrome chk
  for(n=0; n < A->NN; n++) { if(bias[n][0]>0.5)   bp->tt[n] = 0;
                             else                 bp->tt[n] = 1; }
  GenSyndrome2(A, bp->tt, bp->zz);
  if( HamDist(bp->zz, bp->target_z, A->MM)==0 )  return 1;   // if matched, early return syndrome_ok
  //----------------------------------------------

  memcpy ( bp->pn , bias, A->NN*2*sizeof(**bias) );

  for(n=0; n < A->NN; n++) {
    restrict_p2(bp->pn[n]);  // make every pn[n] range restricted

    /*dn[n] = bp->pn[n][0] - bp->pn[n][1];  // gen delta = p0 - p1
    if(fabs(dn[n]) < 2*dlt) { printf("get too small abs from bp->dn[%d] %g , need debug !!! \n", n, dn[n]); getchar(); }

    for(j=0; j < A->num_n[n]; j++) {
      memcpy( bp->qlm[n][j] , bp->pn[n] , 2*sizeof(**bias) ); // bp->qlm[n][j][0]=bp->pn[n][0]; bp->qlm[n][j][1]=bp->pn[n][1];
    }*/

    pn_afv[0] = bp->pn[n][0];   pn_afv[1] = bp->pn[n][1];
  #if ALFA_V
    pn_afv[0] = pow_fast( pn_afv[0] , 10.0/ALFA_V );  pn_afv[1] = pow_fast( pn_afv[1] , 10.0/ALFA_V );
    pn_afv[0] = pn_afv[0]/(pn_afv[0] + pn_afv[1]);    restrict_p2(pn_afv);   // bound pn_afv[0] and gen pn_afv[1]
  #endif
    dn[n] = pn_afv[0] - pn_afv[1];
    if(fabs(dn[n]) < 2*dlt) { printf("too small abs dn[%d] %g , debug !!! \n", n, dn[n]); getchar(); }

    for(j=0; j < A->num_n[n]; j++) {
      memcpy( bp->qlm[n][j] , pn_afv , 2*sizeof(**bias) ); // bp->qlm[n][j][0]=bp->pn[n][0]; bp->qlm[n][j][1]=bp->pn[n][1];
    }
  }
  memcpy ( bp->qn , bp->pn, A->NN*2*sizeof(**bias) );

  for(m=0; m < A->MM; m++) {  // init all dqml[M][j] for 0 <= j < num_m[m]
    for(j=0; j < A->num_m[m]; j++) {
      n = A->mlist[m][j];
      bp->dqml[m][j] = dn[n];
    }
  }
  return 0;
}



//-- BP dec (one call one iter): return 1 syndrome OK, 0 still NG
uint8_t bp2_dec20(BP2_Ctl *bp, a2_matrix *A)
{
  //int32_t  m, n, i , j ;

  int32_t  m, j ;
  //-- Horizontal Step of MacKay's '99 IT paper
  for(m=0; m < A->MM; m++) {  // update all dm[M]
    ////bp->dm[m] = 1.0;
    bp->dm[m] = (double)bp->target_z[m]*(-2) + 1;  // 0 -> 1,  1 -> -1    // SYNDROME_DEC

    for(j=0; j < A->num_m[m]; j++) {
      //n = A->mlist[m][j];
      bp->dm[m] *= bp->dqml[m][j];
    }
    //if(bp->dm[m] == 0) {  printf("hit bp->dm[%d] == 0 , need debug !! \n", m); getchar(); }

    for(j=0; j < A->num_m[m]; j++) {  // update all dml[m][L], L =num_m[m]
      //n = A->mlist[m][j];
      //if(bp->dqml[m][j] == 0) { printf(" !!! to be /bp->dqml[%d][%d]=0 , need debug !!! \n",m,j); getchar(); }
      bp->dml[m][j] = bp->dm[m] / bp->dqml[m][j];
      bp->rml[m][j][0] = (1.0+bp->dml[m][j])/2; // and hence can update rml[0]
      bp->rml[m][j][1] = (1.0-bp->dml[m][j])/2; // and also rml[1]
      //if(!(0<bp->rml[m][j][0]&&bp->rml[m][j][0]<=1)) { printf(" !!! rml[%d][%d][0]=%g out of range , debug !!! \n", m,j,bp->rml[m][j][0]); getchar(); }
      //if(!(0<bp->rml[m][j][1]&&bp->rml[m][j][1]<=1)) { printf(" !!! rml[%d][%d][1]=%g out of range , debug !!! \n", m,j,bp->rml[m][j][1]); getchar(); }
    }
  }

  int32_t  n, i;
  //-- Vertical Step of MacKay's '99 IT paper
  for(n=0; n < A->NN; n++) {
    //- mark this row to use qn
    bp->qn[n][0] = bp->pn[n][0];    bp->qn[n][1] = bp->pn[n][1];

    for(i=0; i < A->num_n[n]; i++) {
      m = A->nlist[n][i];
      j = A->ni2j[n][i];
    #if ALFA
      bp->rml[m][j][0] = pow_fast( bp->rml[m][j][0] , 100.0/ALFA );
      bp->rml[m][j][1] = pow_fast( bp->rml[m][j][1] , 100.0/ALFA );
    #endif
      //if(bp->rml[m][j][0] == 0) { printf(" !!! to be *bp->rml[%d][%d][0]=0 !!! \n", m,j); getchar(); }
      //if(bp->rml[m][j][1] == 0) { printf(" !!! to be *bp->rml[%d][%d][1]=0 !!! \n", m,j); getchar(); }
      //if(bp->rml[m][j][0]==0 && bp->rml[m][j][1]==0) { printf(" !!! both bp->rml[%d][%d][0] and [1] be zero at n = %d !!! \n", m,j,n); getchar(); }

    #if AFP==0
      bp->qn[n][0] *= bp->rml[m][j][0];   bp->qn[n][1] *= bp->rml[m][j][1];
    #else
      bp->qn[n][0] *= pow_fast(bp->rml[m][j][0], 100.0/AFP);    bp->qn[n][1] *= pow_fast(bp->rml[m][j][1], 100.0/AFP);
    #endif
      //if(!(0<=bp->qn[n][0]&&bp->qn[n][0]<=1)) { printf(" !!! bp->qn[%d][0]=%g out of range !!! \n", n,bp->qn[n][0]); getchar(); }
      //if(!(0<=bp->qn[n][1]&&bp->qn[n][1]<=1)) { printf(" !!! bp->qn[%d][1]=%g out of range !!! \n", n,bp->qn[n][1]); getchar(); }
    }
    //- corner values
    /*if(bp->qn[n][0] == 0 && bp->qn[n][1] == 0) { printf("both bp->qn[n][0] = bp->qn[n][0]=0 at n = %d , debug !! \n ", n); getchar(); }
    else if(bp->qn[n][0] == 0) { printf("both bp->qn[n][0] =0 at n = %d , debug !! \n ", n); getchar(); }
    else if(bp->qn[n][1] == 0) { printf("both bp->qn[n][1] =0 at n = %d , debug !! \n ", n); getchar(); }*/

    for(i=0; i < A->num_n[n]; i++) {
      m = A->nlist[n][i];
      j = A->ni2j[n][i];
      //if(bp->rml[m][j][0] == 0) { printf(" !!! to be bp->qn[n][0]=%g/bp->rml[%d][%d][0]=0 at n = %d !!! \n", bp->qn[n][0],m,j,n); getchar(); }
      //if(bp->rml[m][j][1] == 0) { printf(" !!! to be bp->qn[n][0]=%g/bp->rml[%d][%d][1]=0 at n = %d !!! \n", bp->qn[n][1],m,j,n); getchar(); }
      bp->qlm[n][i][0] = bp->qn[n][0]/bp->rml[m][j][0];   bp->qlm[n][i][1] = bp->qn[n][1]/bp->rml[m][j][1];

    #if ALFA_V
      bp->qlm[n][i][0] = pow_fast( bp->qlm[n][i][0] , 10.0/ALFA_V );  bp->qlm[n][i][1] = pow_fast( bp->qlm[n][i][1] , 10.0/ALFA_V );
    #endif

      //- normalizing qlm
      bp->qlm[n][i][0] = bp->qlm[n][i][0]/(bp->qlm[n][i][0]+bp->qlm[n][i][1]);   //bp->qlm[n][i][1] = 1.0 - bp->qlm[n][i][0];
      restrict_p2(bp->qlm[n][i]);
      //- update dqml
      bp->dqml[m][j] = bp->qlm[n][i][0] - bp->qlm[n][i][1];
      //if(fabs(bp->dqml[m][j]) < 2*dlt) { printf("get too small abs from bp->dqml[%d][%d] %g , need debug !!! \n", m,j,bp->dqml[m][j]); getchar(); }
    }
    //- normalizing qn (can skip now)
    ////bp->qn[n][0] = bp->qn[n][0]/(bp->qn[n][0]+bp->qn[n][1]);    //bp->qn[n][1] = 1.0 - bp->qn[n][0];
    ////restrict_p2(bp->qn[n])
  }

  //-- Syndrome Checking
  for(n=0; n < A->NN; n++) {
    ////if(bp->qn[n][0] > 0.5)    bp->tt[n] = 0;
    ////else                      bp->tt[n] = 1;
    if(bp->qn[n][0] > bp->qn[n][1])  bp->tt[n] = 0;   // use this as we don't have qn normalized now
    else                             bp->tt[n] = 1;   // use this as we don't have qn normalized now
  }
  GenSyndrome2(A, bp->tt, bp->zz);
  ////if( is_zero_vec(bp->zz, M) )  return 1;
  ////else                          return 0;
  if( 0 == HamDist(bp->zz, bp->target_z, A->MM) )  return 1;    // SYNDROME_DEC
  else                                             return 0;    // SYNDROME_DEC
}


//-- base on bp_dec4 but decode to target_z (support SYNDROME_DEC)
uint8_t bp2_dec24(BP2_Ctl *bp, a2_matrix *A)
{
  int32_t  m, n, i , j ;

  for(m=0; m < A->MM; m++) {  // make all dm[M] ready first!!
    //bp->dm[m] = 1.0;                                                            // NO_TARGET_Z
    bp->dm[m] = (double)bp->target_z[m]*(-2) + 1;  // zm 0 -> 1,  zm 1 -> -1      // BY_TARGET_Z

    for(j=0; j < A->num_m[m]; j++) { bp->dm[m] *= bp->dqml[m][j]; }
  }

  for(n=0; n < A->NN; n++) {
    bp->qn[n][0] = bp->pn[n][0];    bp->qn[n][1] = bp->pn[n][1];

    for(i=0; i < A->num_n[n]; i++) {  // update n <- dml[m][j]
      m = A->nlist[n][i];
      j = A->ni2j[n][i];
      bp->dml[m][j] = bp->dm[m] / bp->dqml[m][j];
      bp->rml[m][j][0] = (1.0+bp->dml[m][j])/2; // and hence can update rml[0]
      bp->rml[m][j][1] = (1.0-bp->dml[m][j])/2; // and also rml[1]
    #if ALFA
      bp->rml[m][j][0] = pow_fast( bp->rml[m][j][0] , 100.0/ALFA );
      bp->rml[m][j][1] = pow_fast( bp->rml[m][j][1] , 100.0/ALFA );
    #endif

    #if AFP==0
      bp->qn[n][0] *= bp->rml[m][j][0];   bp->qn[n][1] *= bp->rml[m][j][1];
    #else
      bp->qn[n][0] *= pow_fast(bp->rml[m][j][0], 100.0/AFP);    bp->qn[n][1] *= pow_fast(bp->rml[m][j][1], 100.0/AFP);
    #endif
    }

    for(i=0; i < A->num_n[n]; i++) {  // update qlm[n][i] -> m  (by delta and m-friendly index dqml[m][j] -> m)
      m = A->nlist[n][i];
      j = A->ni2j[n][i];
      bp->qlm[n][i][0] = bp->qn[n][0]/bp->rml[m][j][0];   bp->qlm[n][i][1] = bp->qn[n][1]/bp->rml[m][j][1];
    #if ALFA_V
      bp->qlm[n][i][0] = pow_fast( bp->qlm[n][i][0] , 10.0/ALFA_V );  bp->qlm[n][i][1] = pow_fast( bp->qlm[n][i][1] , 10.0/ALFA_V );
    #endif
      //- normalizing qlm
      bp->qlm[n][i][0] = bp->qlm[n][i][0]/(bp->qlm[n][i][0]+bp->qlm[n][i][1]);   //bp->qlm[n][i][1] = 1.0 - bp->qlm[n][i][0];
      restrict_p2(bp->qlm[n][i]);
      //- update dqml
      bp->dqml[m][j] = bp->qlm[n][i][0] - bp->qlm[n][i][1];

      //- make dm more updated
      bp->dm[m] = bp->dml[m][j] * bp->dqml[m][j];
    }
    //- normalizing qn (can skip now)
    ////bp->qn[n][0] = bp->qn[n][0]/(bp->qn[n][0]+bp->qn[n][1]);    //bp->qn[n][1] = 1.0 - bp->qn[n][0];
    ////restrict_p2(bp->qn[n])
  }

  //-- Syndrome Checking
  for(n=0; n < A->NN; n++) {
    ////if(bp->qn[n][0] > 0.5)    bp->tt[n] = 0;
    ////else                      bp->tt[n] = 1;
    if(bp->qn[n][0] > bp->qn[n][1])  bp->tt[n] = 0;   // use this as we don't have qn normalized now
    else                             bp->tt[n] = 1;   // use this as we don't have qn normalized now
  }
  GenSyndrome2(A, bp->tt, bp->zz);
  /*if( is_zero_vec(bp->zz, M) )  return 1;                   // NO_TARGET_Z
  else                          return 0;*/
  if( 0 == HamDist(bp->zz, bp->target_z, A->MM) )  return 1;  // BY_TARGET_Z
  else                                             return 0;
}

#endif  // USE_GF2_DEC


